import type { Country, SupportedLanguage } from '@/types';

const i18n_COUNTRIES: Record<string, Record<SupportedLanguage, string>> = {
  us: {
    en: 'United States of America',
    ar: 'الولايات المتحدة',
    az: 'Amerika Birləşmiş Ştatları',
    de: 'Vereinigte Staaten',
    es: 'Estados Unidos',
    fa: 'ایالات متحده آمریکا',
    fr: 'États-Unis',
    id: 'Amerika Serikat',
    it: "Stati Uniti d'America",
    kk: 'Америка Құрама Штаттары',
    ko: '미국',
    ky: 'АКШ',
    ms: 'Amerika Syarikat',
    ru: 'США',
    tr: 'Amerika Birleşik Devletleri',
    zh: '美國',
  },
  cn: {
    en: 'China',
    ar: 'الصين',
    az: 'Çin',
    de: 'Volksrepublik China',
    es: 'República Popular China',
    fa: 'جمهوری خلق چین',
    fr: 'république populaire de Chine',
    id: 'Republik Rakyat Tiongkok',
    it: 'Cina',
    kk: 'Қытай Халық Республикасы',
    ko: '중화인민공화국',
    ky: 'Кытай',
    ms: 'Republik Rakyat China',
    ru: 'Китай',
    tr: 'Çin Halk Cumhuriyeti',
    zh: '中华人民共和国',
  },
  au: {
    en: 'Australia',
    ar: 'أستراليا',
    az: 'Avstraliya',
    de: 'Australien',
    es: 'Australia',
    fa: 'استرالیا',
    fr: 'Australie',
    id: 'Australia',
    it: 'Australia',
    kk: 'Аустралия',
    ko: '오스트레일리아',
    ky: 'Австралия',
    ms: 'Australia',
    ru: 'Австралия',
    tr: 'Avustralya',
    zh: '澳大利亚',
  },
  jp: {
    en: 'Japan',
    ar: 'اليابان',
    az: 'Yaponiya',
    de: 'Japan',
    es: 'Japón',
    fa: 'ژاپن',
    fr: 'Japon',
    id: 'Jepang',
    it: 'Giappone',
    kk: 'Жапония',
    ko: '일본',
    ky: 'Жапония',
    ms: 'Jepun',
    ru: 'Япония',
    tr: 'Japonya',
    zh: '日本',
  },
  th: {
    en: 'Thailand',
    ar: 'تايلاند',
    az: 'Tailand',
    de: 'Thailand',
    es: 'Tailandia',
    fa: 'تایلند',
    fr: 'Thaïlande',
    id: 'Thailand',
    it: 'Thailandia',
    kk: 'Тайланд',
    ko: '태국',
    ky: 'Таиланд',
    ms: 'Thailand',
    ru: 'Таиланд',
    tr: 'Tayland',
    zh: '泰國',
  },
  in: {
    en: 'India',
    ar: 'الهند',
    az: 'Hindistan',
    de: 'Indien',
    es: 'India',
    fa: 'هند',
    fr: 'Inde',
    id: 'India',
    it: 'India',
    kk: 'Үндістан',
    ko: '인도',
    ky: 'Индия',
    ms: 'India',
    ru: 'Индия',
    tr: 'Hindistan',
    zh: '印度',
  },
  my: {
    en: 'Malaysia',
    ar: 'ماليزيا',
    az: 'Malayziya',
    de: 'Malaysia',
    es: 'Malasia',
    fa: 'مالزی',
    fr: 'Malaisie',
    id: 'Malaysia',
    it: 'Malaysia',
    kk: 'Малайзия',
    ko: '말레이시아',
    ky: 'Малайзия',
    ms: 'Malaysia',
    ru: 'Малайзия',
    tr: 'Malezya',
    zh: '馬來西亞',
  },
  sg: {
    en: 'Singapore',
    ar: 'سنغافورة',
    az: 'Sinqapur',
    de: 'Singapur',
    es: 'Singapur',
    fa: 'سنگاپور',
    fr: 'Singapour',
    id: 'Singapura',
    it: 'Singapore',
    kk: 'Сингапур',
    ko: '싱가포르',
    ky: 'Сингапур, мамлекет',
    ms: 'Singapura',
    ru: 'Сингапур',
    tr: 'Singapur',
    zh: '新加坡',
  },
  hk: {
    en: 'Hong Kong',
    ar: 'هونغ كونغ',
    az: 'Honkonq',
    de: 'Hongkong',
    es: 'Hong Kong',
    fa: 'هنگ کنگ',
    fr: 'Hong Kong',
    id: 'Hong Kong',
    it: 'Hong Kong',
    kk: 'Гонконг',
    ko: '홍콩',
    ky: 'Гонконг',
    ms: 'Hong Kong',
    ru: 'Гонконг',
    tr: 'Hong Kong',
    zh: '香港',
  },
  kh: {
    en: 'Cambodia',
    ar: 'كمبوديا',
    az: 'Kamboca',
    de: 'Kambodscha',
    es: 'Camboya',
    fa: 'کامبوج',
    fr: 'Cambodge',
    id: 'Kamboja',
    it: 'Cambogia',
    kk: 'Камбоджа',
    ko: '캄보디아',
    ky: 'Камбожа',
    ms: 'Kemboja',
    ru: 'Камбоджа',
    tr: 'Kamboçya',
    zh: '柬埔寨',
  },
  ph: {
    en: 'Philippines',
    ar: 'الفلبين',
    az: 'Filippin',
    de: 'Philippinen',
    es: 'Filipinas',
    fa: 'فیلیپین',
    fr: 'Philippines',
    id: 'Filipina',
    it: 'Filippine',
    kk: 'Филиппиндер',
    ko: '필리핀',
    ky: 'Филиппиндер',
    ms: 'Filipina',
    ru: 'Филиппины',
    tr: 'Filipinler',
    zh: '菲律賓',
  },
  vn: {
    en: 'Viet Nam',
    ar: 'فيتنام',
    az: 'Vyetnam',
    de: 'Vietnam',
    es: 'Vietnam',
    fa: 'ویتنام',
    fr: 'Viêt Nam',
    id: 'Vietnam',
    it: 'Vietnam',
    kk: 'Вьетнам',
    ko: '베트남',
    ky: 'Вьетнам',
    ms: 'Vietnam',
    ru: 'Вьетнам',
    tr: 'Vietnam',
    zh: '越南',
  },
  no: {
    en: 'Norway',
    ar: 'النرويج',
    az: 'Norveç',
    de: 'Norwegen',
    es: 'Noruega',
    fa: 'نروژ',
    fr: 'Norvège',
    id: 'Norwegia',
    it: 'Norvegia',
    kk: 'Норвегия',
    ko: '노르웨이',
    ky: 'Норвегия',
    ms: 'Norway',
    ru: 'Норвегия',
    tr: 'Norveç',
    zh: '挪威',
  },
  br: {
    en: 'Brazil',
    ar: 'البرازيل',
    az: 'Braziliya',
    de: 'Brasilien',
    es: 'Brasil',
    fa: 'برزیل',
    fr: 'Brésil',
    id: 'Brasil',
    it: 'Brasile',
    kk: 'Бразилия',
    ko: '브라질',
    ky: 'Бразилия',
    ms: 'Brazil',
    ru: 'Бразилия',
    tr: 'Brezilya',
    zh: '巴西',
  },
  ar: {
    en: 'Argentina',
    ar: 'الأرجنتين',
    az: 'Argentina',
    de: 'Argentinien',
    es: 'Argentina',
    fa: 'آرژانتین',
    fr: 'Argentine',
    id: 'Argentina',
    it: 'Argentina',
    kk: 'Аргентина',
    ko: '아르헨티나',
    ky: 'Аргентина',
    ms: 'Argentina',
    ru: 'Аргентина',
    tr: 'Arjantin',
    zh: '阿根廷',
  },
  ps: {
    en: 'Palestine, State of',
    ar: 'دولة فلسطين',
    az: 'Fələstin Dövləti',
    de: 'Staat Palästina',
    es: 'Estado de Palestina',
    fa: 'دولت فلسطین',
    fr: 'État de Palestine',
    id: 'Negara Palestina',
    it: 'Palestina',
    kk: 'Палестина мемлекеті',
    ko: '팔레스타인',
    ky: 'Палестина Мамлекети',
    ms: 'Negara Palestin',
    ru: 'Государство Палестина',
    tr: 'Filistin Devleti',
    zh: '巴勒斯坦',
  },
  es: {
    en: 'Spain',
    ar: 'إسبانيا',
    az: 'İspaniya',
    de: 'Spanien',
    es: 'España',
    fa: 'اسپانیا',
    fr: 'Espagne',
    id: 'Spanyol',
    it: 'Spagna',
    kk: 'Испания',
    ko: '스페인',
    ky: 'Испания',
    ms: 'Sepanyol',
    ru: 'Испания',
    tr: 'İspanya',
    zh: '西班牙',
  },
  fr: {
    en: 'France',
    ar: 'فرنسا',
    az: 'Fransa',
    de: 'Frankreich',
    es: 'Francia',
    fa: 'فرانسه',
    fr: 'France',
    id: 'Prancis',
    it: 'Francia',
    kk: 'Франция',
    ko: '프랑스',
    ky: 'Франция',
    ms: 'Perancis',
    ru: 'Франция',
    tr: 'Fransa',
    zh: '法國',
  },
  de: {
    en: 'Germany',
    ar: 'ألمانيا',
    az: 'Almaniya',
    de: 'Deutschland',
    es: 'Alemania',
    fa: 'آلمان',
    fr: 'Allemagne',
    id: 'Jerman',
    it: 'Germania',
    kk: 'Германия',
    ko: '독일',
    ky: 'Германия',
    ms: 'Jerman',
    ru: 'Германия',
    tr: 'Almanya',
    zh: '德國',
  },
  it: {
    en: 'Italy',
    ar: 'إيطاليا',
    az: 'İtaliya',
    de: 'Italien',
    es: 'Italia',
    fa: 'ایتالیا',
    fr: 'Italie',
    id: 'Italia',
    it: 'Italia',
    kk: 'Италия',
    ko: '이탈리아',
    ky: 'Италия',
    ms: 'Itali',
    ru: 'Италия',
    tr: 'İtalya',
    zh: '意大利',
  },
  at: {
    en: 'Austria',
    ar: 'النمسا',
    az: 'Avstriya',
    de: 'Österreich',
    es: 'Austria',
    fa: 'اتریش',
    fr: 'Autriche',
    id: 'Austria',
    it: 'Austria',
    kk: 'Аустрия',
    ko: '오스트리아',
    ky: 'Австрия',
    ms: 'Austria',
    ru: 'Австрия',
    tr: 'Avusturya',
    zh: '奧地利',
  },
  ch: {
    en: 'Switzerland',
    ar: 'سويسرا',
    az: 'İsveçrə',
    de: 'Schweiz',
    es: 'Suiza',
    fa: 'سوئیس',
    fr: 'Suisse',
    id: 'Swiss',
    it: 'Svizzera',
    kk: 'Швейцария',
    ko: '스위스',
    ky: 'Швейцария',
    ms: 'Switzerland',
    ru: 'Швейцария',
    tr: 'İsviçre',
    zh: '瑞士',
  },
  za: {
    en: 'South Africa',
    ar: 'جنوب إفريقيا',
    az: 'Cənubi Afrika Respublikası',
    de: 'Südafrika',
    es: 'Sudáfrica',
    fa: 'آفریقای جنوبی',
    fr: 'Afrique du Sud',
    id: 'Afrika Selatan',
    it: 'Sudafrica',
    kk: 'Оңтүстік Африка Республикасы',
    ko: '남아프리카 공화국',
    ky: 'Түштүк-Африка Республикасы',
    ms: 'Afrika Selatan',
    ru: 'ЮАР',
    tr: 'Güney Afrika Cumhuriyeti',
    zh: '南非',
  },
  gr: {
    en: 'Greece',
    ar: 'اليونان',
    az: 'Yunanıstan',
    de: 'Griechenland',
    es: 'Grecia',
    fa: 'یونان',
    fr: 'Grèce',
    id: 'Yunani',
    it: 'Grecia',
    kk: 'Грекия',
    ko: '그리스',
    ky: 'Греция',
    ms: 'Yunani',
    ru: 'Греция',
    tr: 'Yunanistan',
    zh: '希腊',
  },
  se: {
    en: 'Sweden',
    ar: 'السويد',
    az: 'İsveç',
    de: 'Schweden',
    es: 'Suecia',
    fa: 'سوئد',
    fr: 'Suède',
    id: 'Swedia',
    it: 'Svezia',
    kk: 'Швеция',
    ko: '스웨덴',
    ky: 'Швеция',
    ms: 'Sweden',
    ru: 'Швеция',
    tr: 'İsveç',
    zh: '瑞典',
  },
  ae: {
    en: 'United Arab Emirates',
    ar: 'الإمارات العربية المتحدة',
    az: 'Birləşmiş Ərəb Əmirlikləri',
    de: 'Vereinigte Arabische Emirate',
    es: 'Emiratos Árabes Unidos',
    fa: 'امارات متحده عربی',
    fr: 'Émirats arabes unis',
    id: 'Uni Emirat Arab',
    it: 'Emirati Arabi Uniti',
    kk: 'Біріккен Араб Әмірліктері',
    ko: '아랍에미리트',
    ky: 'Бириккен Араб Эмирликтери',
    ms: 'Emiriah Arab Bersatu',
    ru: 'Объединённые Арабские Эмираты',
    tr: 'Birleşik Arap Emirlikleri',
    zh: '阿拉伯联合酋长国',
  },
  be: {
    en: 'Belgium',
    ar: 'بلجيكا',
    az: 'Belçika',
    de: 'Belgien',
    es: 'Bélgica',
    fa: 'بلژیک',
    fr: 'Belgique',
    id: 'Belgia',
    it: 'Belgio',
    kk: 'Бельгия',
    ko: '벨기에',
    ky: 'Бельгия',
    ms: 'Belgium',
    ru: 'Бельгия',
    tr: 'Belçika',
    zh: '比利時',
  },
  dk: {
    en: 'Denmark',
    ar: 'الدنمارك',
    az: 'Danimarka',
    de: 'Dänemark',
    es: 'Dinamarca',
    fa: 'دانمارک',
    fr: 'Danemark',
    id: 'Denmark',
    it: 'Danimarca',
    kk: 'Дания',
    ko: '덴마크',
    ky: 'Дания',
    ms: 'Denmark',
    ru: 'Дания',
    tr: 'Danimarka',
    zh: '丹麥',
  },
  pt: {
    en: 'Portugal',
    ar: 'البرتغال',
    az: 'Portuqaliya',
    de: 'Portugal',
    es: 'Portugal',
    fa: 'پرتغال',
    fr: 'Portugal',
    id: 'Portugal',
    it: 'Portogallo',
    kk: 'Португалия',
    ko: '포르투갈',
    ky: 'Португалия',
    ms: 'Portugal',
    ru: 'Португалия',
    tr: 'Portekiz',
    zh: '葡萄牙',
  },
  gh: {
    en: 'Ghana',
    ar: 'غانا',
    az: 'Qana',
    de: 'Ghana',
    es: 'Ghana',
    fa: 'غنا',
    fr: 'Ghana',
    id: 'Ghana',
    it: 'Ghana',
    kk: 'Гана',
    ko: '가나',
    ky: 'Гана',
    ms: 'Ghana',
    ru: 'Гана',
    tr: 'Gana',
    zh: '迦納',
  },
  cm: {
    en: 'Cameroon',
    ar: 'الكاميرون',
    az: 'Kamerun',
    de: 'Kamerun',
    es: 'Camerún',
    fa: 'کامرون',
    fr: 'Cameroun',
    id: 'Kamerun',
    it: 'Camerun',
    kk: 'Камерун',
    ko: '카메룬',
    ky: 'Камерун',
    ms: 'Cameroon',
    ru: 'Камерун',
    tr: 'Kamerun',
    zh: '喀麦隆',
  },
  tr: {
    en: 'Turkiye',
    ar: 'تركيا',
    az: 'Türkiyə',
    de: 'Türkei',
    es: 'Turquía',
    fa: 'ترکیه',
    fr: 'Turquie',
    id: 'Turki',
    it: 'Turchia',
    kk: 'Түркия',
    ko: '튀르키예',
    ky: 'Түркия',
    ms: 'Turki',
    ru: 'Турция',
    tr: 'Türkiye',
    zh: '土耳其',
  },
  fi: {
    en: 'Finland',
    ar: 'فنلندا',
    az: 'Finlandiya',
    de: 'Finnland',
    es: 'Finlandia',
    fa: 'فنلاند',
    fr: 'Finlande',
    id: 'Finlandia',
    it: 'Finlandia',
    kk: 'Финляндия',
    ko: '핀란드',
    ky: 'Финляндия',
    ms: 'Finland',
    ru: 'Финляндия',
    tr: 'Finlandiya',
    zh: '芬蘭',
  },
  pl: {
    en: 'Poland',
    ar: 'بولندا',
    az: 'Polşa',
    de: 'Polen',
    es: 'Polonia',
    fa: 'لهستان',
    fr: 'Pologne',
    id: 'Polandia',
    it: 'Polonia',
    kk: 'Польша',
    ko: '폴란드',
    ky: 'Польша',
    ms: 'Poland',
    ru: 'Польша',
    tr: 'Polonya',
    zh: '波蘭',
  },
  jo: {
    en: 'Jordan',
    ar: 'الأردن',
    az: 'İordaniya',
    de: 'Jordanien',
    es: 'Jordania',
    fa: 'اردن',
    fr: 'Jordanie',
    id: 'Yordania',
    it: 'Giordania',
    kk: 'Иордания',
    ko: '요르단',
    ky: 'Иордания',
    ms: 'Jordan',
    ru: 'Иордания',
    tr: 'Ürdün',
    zh: '約旦',
  },
  ro: {
    en: 'Romania',
    ar: 'رومانيا',
    az: 'Rumıniya',
    de: 'Rumänien',
    es: 'Rumania',
    fa: 'رومانی',
    fr: 'Roumanie',
    id: 'Rumania',
    it: 'Romania',
    kk: 'Румыния',
    ko: '루마니아',
    ky: 'Румыния',
    ms: 'Romania',
    ru: 'Румыния',
    tr: 'Romanya',
    zh: '羅馬尼亞',
  },
  ke: {
    en: 'Kenya',
    ar: 'كينيا',
    az: 'Keniya',
    de: 'Kenia',
    es: 'Kenia',
    fa: 'کنیا',
    fr: 'Kenya',
    id: 'Kenya',
    it: 'Kenya',
    kk: 'Кения',
    ko: '케냐',
    ky: 'Кения',
    ms: 'Kenya',
    ru: 'Кения',
    tr: 'Kenya',
    zh: '肯尼亚',
  },
  ie: {
    en: 'Ireland',
    ar: 'جمهورية أيرلندا',
    az: 'İrlandiya',
    de: 'Irland',
    es: 'Irlanda',
    fa: 'ایرلند',
    fr: 'Irlande',
    id: 'Republik Irlandia',
    it: 'Irlanda',
    kk: 'Ирландия',
    ko: '아일랜드',
    ky: 'Ирландия',
    ms: 'Ireland',
    ru: 'Ирландия',
    tr: 'İrlanda',
    zh: '愛爾蘭共和國',
  },
  ug: {
    en: 'Uganda',
    ar: 'أوغندا',
    az: 'Uqanda',
    de: 'Uganda',
    es: 'Uganda',
    fa: 'اوگاندا',
    fr: 'Ouganda',
    id: 'Uganda',
    it: 'Uganda',
    kk: 'Уганда',
    ko: '우간다',
    ky: 'Уганда',
    ms: 'Uganda',
    ru: 'Уганда',
    tr: 'Uganda',
    zh: '烏干達',
  },
  am: {
    en: 'Armenia',
    ar: 'أرمينيا',
    az: 'Ermənistan',
    de: 'Armenien',
    es: 'Armenia',
    fa: 'ارمنستان',
    fr: 'Arménie',
    id: 'Armenia',
    it: 'Armenia',
    kk: 'Армения',
    ko: '아르메니아',
    ky: 'Армения',
    ms: 'Armenia',
    ru: 'Армения',
    tr: 'Ermenistan',
    zh: '亞美尼亞',
  },
  bi: {
    en: 'Burundi',
    ar: 'بوروندي',
    az: 'Burundi',
    de: 'Burundi',
    es: 'Burundi',
    fa: 'بوروندی',
    fr: 'Burundi',
    id: 'Burundi',
    it: 'Burundi',
    kk: 'Бурунди',
    ko: '부룬디',
    ky: 'Бурунди',
    ms: 'Burundi',
    ru: 'Бурунди',
    tr: 'Burundi',
    zh: '蒲隆地',
  },
  lu: {
    en: 'Luxembourg',
    ar: 'لوكسمبورغ',
    az: 'Lüksemburq',
    de: 'Luxemburg',
    es: 'Luxemburgo',
    fa: 'لوکزامبورگ',
    fr: 'Luxembourg',
    id: 'Luksemburg',
    it: 'Lussemburgo',
    kk: 'Люксембург',
    ko: '룩셈부르크',
    ky: 'Люксембург',
    ms: 'Luxembourg',
    ru: 'Люксембург',
    tr: 'Lüksemburg',
    zh: '卢森堡',
  },
  co: {
    en: 'Colombia',
    ar: 'كولومبيا',
    az: 'Kolumbiya',
    de: 'Kolumbien',
    es: 'Colombia',
    fa: 'کلمبیا',
    fr: 'Colombie',
    id: 'Kolombia',
    it: 'Colombia',
    kk: 'Колумбия Республикасы',
    ko: '콜롬비아',
    ky: 'Колумбия',
    ms: 'Colombia',
    ru: 'Колумбия',
    tr: 'Kolombiya',
    zh: '哥伦比亚',
  },
  pe: {
    en: 'Peru',
    ar: 'بيرو',
    az: 'Peru',
    de: 'Peru',
    es: 'Perú',
    fa: 'پرو',
    fr: 'Pérou',
    id: 'Peru',
    it: 'Perù',
    kk: 'Перу',
    ko: '페루',
    ky: 'Перу',
    ms: 'Peru',
    ru: 'Перу',
    tr: 'Peru',
    zh: '秘鲁',
  },
  bg: {
    en: 'Bulgaria',
    ar: 'بلغاريا',
    az: 'Bolqarıstan',
    de: 'Bulgarien',
    es: 'Bulgaria',
    fa: 'بلغارستان',
    fr: 'Bulgarie',
    id: 'Bulgaria',
    it: 'Bulgaria',
    kk: 'Болгария',
    ko: '불가리아',
    ky: 'Болгария',
    ms: 'Bulgaria',
    ru: 'Болгария',
    tr: 'Bulgaristan',
    zh: '保加利亚',
  },
  cl: {
    en: 'Chile',
    ar: 'تشيلي',
    az: 'Çili',
    de: 'Chile',
    es: 'Chile',
    fa: 'شیلی',
    fr: 'Chili',
    id: 'Chili',
    it: 'Cile',
    kk: 'Чили',
    ko: '칠레',
    ky: 'Чили',
    ms: 'Chile',
    ru: 'Чили',
    tr: 'Şili',
    zh: '智利',
  },
  ua: {
    en: 'Ukraine',
    ar: 'أوكرانيا',
    az: 'Ukrayna',
    de: 'Ukraine',
    es: 'Ucrania',
    fa: 'اوکراین',
    fr: 'Ukraine',
    id: 'Ukraina',
    it: 'Ucraina',
    kk: 'Украина',
    ko: '우크라이나',
    ky: 'Украина',
    ms: 'Ukraine',
    ru: 'Украина',
    tr: 'Ukrayna',
    zh: '烏克蘭',
  },
  eg: {
    en: 'Egypt',
    ar: 'مصر',
    az: 'Misir',
    de: 'Ägypten',
    es: 'Egipto',
    fa: 'مصر',
    fr: 'Égypte',
    id: 'Mesir',
    it: 'Egitto',
    kk: 'Мысыр',
    ko: '이집트',
    ky: 'Египет',
    ms: 'Mesir',
    ru: 'Египет',
    tr: 'Mısır',
    zh: '埃及',
  },
  ca: {
    en: 'Canada',
    ar: 'كندا',
    az: 'Kanada',
    de: 'Kanada',
    es: 'Canadá',
    fa: 'کانادا',
    fr: 'Canada',
    id: 'Kanada',
    it: 'Canada',
    kk: 'Канада',
    ko: '캐나다',
    ky: 'Канада',
    ms: 'Kanada',
    ru: 'Канада',
    tr: 'Kanada',
    zh: '加拿大',
  },
  il: {
    en: 'Israel',
    ar: 'إسرائيل',
    az: 'İsrail',
    de: 'Israel',
    es: 'Israel',
    fa: 'اسرائیل',
    fr: 'Israël',
    id: 'Israel',
    it: 'Israele',
    kk: 'Израиль',
    ko: '이스라엘',
    ky: 'Израиль',
    ms: 'Israel',
    ru: 'Израиль',
    tr: 'İsrail',
    zh: '以色列',
  },
  qa: {
    en: 'Qatar',
    ar: 'قطر',
    az: 'Qətər',
    de: 'Katar',
    es: 'Catar',
    fa: 'قطر',
    fr: 'Qatar',
    id: 'Qatar',
    it: 'Qatar',
    kk: 'Катар',
    ko: '카타르',
    ky: 'Катар',
    ms: 'Qatar',
    ru: 'Катар',
    tr: 'Katar',
    zh: '卡塔尔',
  },
  sc: {
    en: 'Seychelles',
    ar: 'سيشل',
    az: 'Seyşel adaları',
    de: 'Seychellen',
    es: 'Seychelles',
    fa: 'سیشل',
    fr: 'Seychelles',
    id: 'Seychelles',
    it: 'Seychelles',
    kk: 'Сейшель Аралдары',
    ko: '세이셸',
    ky: 'Сейшел Аралдары',
    ms: 'Seychelles',
    ru: 'Сейшельские Острова',
    tr: 'Seyşeller',
    zh: '塞舌尔',
  },
  iq: {
    en: 'Iraq',
    ar: 'العراق',
    az: 'İraq',
    de: 'Irak',
    es: 'Irak',
    fa: 'عراق',
    fr: 'Irak',
    id: 'Irak',
    it: 'Iraq',
    kk: 'Ирак',
    ko: '이라크',
    ky: 'Ирак',
    ms: 'Iraq',
    ru: 'Ирак',
    tr: 'Irak',
    zh: '伊拉克',
  },
  lv: {
    en: 'Latvia',
    ar: 'لاتفيا',
    az: 'Latviya',
    de: 'Lettland',
    es: 'Letonia',
    fa: 'لتونی',
    fr: 'Lettonie',
    id: 'Latvia',
    it: 'Lettonia',
    kk: 'Латвия',
    ko: '라트비아',
    ky: 'Латвия',
    ms: 'Latvia',
    ru: 'Латвия',
    tr: 'Letonya',
    zh: '拉脫維亞',
  },
  ee: {
    en: 'Estonia',
    ar: 'إستونيا',
    az: 'Estoniya',
    de: 'Estland',
    es: 'Estonia',
    fa: 'استونی',
    fr: 'Estonie',
    id: 'Estonia',
    it: 'Estonia',
    kk: 'Эстония',
    ko: '에스토니아',
    ky: 'Эстония',
    ms: 'Estonia',
    ru: 'Эстония',
    tr: 'Estonya',
    zh: '愛沙尼亞',
  },
  is: {
    en: 'Iceland',
    ar: 'آيسلندا',
    az: 'İslandiya',
    de: 'Island',
    es: 'Islandia',
    fa: 'ایسلند',
    fr: 'Islande',
    id: 'Islandia',
    it: 'Islanda',
    kk: 'Исландия',
    ko: '아이슬란드',
    ky: 'Исландия',
    ms: 'Iceland',
    ru: 'Исландия',
    tr: 'İzlanda',
    zh: '冰島',
  },
  ge: {
    en: 'Georgia',
    ar: 'جورجيا',
    az: 'Corciya',
    de: 'Georgia',
    es: 'Georgia',
    fa: 'جورجیا',
    fr: 'Géorgie',
    id: 'Georgia',
    it: 'Georgia',
    kk: 'Джорджия',
    ko: '조지아주',
    ky: 'Жоржия',
    ms: 'Georgia',
    ru: 'Джорджия',
    tr: 'Georgia',
    zh: '喬治亞州',
  },
  sk: {
    en: 'Slovakia',
    ar: 'سلوفاكيا',
    az: 'Slovakiya',
    de: 'Slowakei',
    es: 'Eslovaquia',
    fa: 'اسلواکی',
    fr: 'Slovaquie',
    id: 'Slowakia',
    it: 'Slovacchia',
    kk: 'Словакия',
    ko: '슬로바키아',
    ky: 'Словакия',
    ms: 'Slovakia',
    ru: 'Словакия',
    tr: 'Slovakya',
    zh: '斯洛伐克',
  },
  kz: {
    en: 'Kazakhstan',
    ar: 'كازاخستان',
    az: 'Qazaxıstan',
    de: 'Kasachstan',
    es: 'Kazajistán',
    fa: 'قزاقستان',
    fr: 'Kazakhstan',
    id: 'Kazakhstan',
    it: 'Kazakistan',
    kk: 'Қазақстан',
    ko: '카자흐스탄',
    ky: 'Казакстан',
    ms: 'Kazakhstan',
    ru: 'Казахстан',
    tr: 'Kazakistan',
    zh: '哈萨克斯坦',
  },
  hr: {
    en: 'Croatia',
    ar: 'كرواتيا',
    az: 'Xorvatiya',
    de: 'Kroatien',
    es: 'Croacia',
    fa: 'کرواسی',
    fr: 'Croatie',
    id: 'Kroasia',
    it: 'Croazia',
    kk: 'Хорватия',
    ko: '크로아티아',
    ky: 'Хорватия',
    ms: 'Croatia',
    ru: 'Хорватия',
    tr: 'Hırvatistan',
    zh: '克羅地亞',
  },
  mx: {
    en: 'Mexico',
    ar: 'المكسيك',
    az: 'Meksika',
    de: 'Mexiko',
    es: 'México',
    fa: 'مکزیک',
    fr: 'Mexique',
    id: 'Meksiko',
    it: 'Messico',
    kk: 'Мексика',
    ko: '멕시코',
    ky: 'Мексика',
    ms: 'Mexico',
    ru: 'Мексика',
    tr: 'Meksika',
    zh: '墨西哥',
  },
  hu: {
    en: 'Hungary',
    ar: 'المجر',
    az: 'Macarıstan',
    de: 'Ungarn',
    es: 'Hungría',
    fa: 'مجارستان',
    fr: 'Hongrie',
    id: 'Hungaria',
    it: 'Ungheria',
    kk: 'Мажарстан',
    ko: '헝가리',
    ky: 'Венгрия',
    ms: 'Hungary',
    ru: 'Венгрия',
    tr: 'Macaristan',
    zh: '匈牙利',
  },
  sa: {
    en: 'Saudi Arabia',
    ar: 'السعودية',
    az: 'Səudiyyə Ərəbistanı',
    de: 'Saudi-Arabien',
    es: 'Arabia Saudí',
    fa: 'عربستان سعودی',
    fr: 'Arabie saoudite',
    id: 'Arab Saudi',
    it: 'Arabia Saudita',
    kk: 'Сауд Арабиясы',
    ko: '사우디아라비아',
    ky: 'Сауд Арабия Падышалыгы',
    ms: 'Arab Saudi',
    ru: 'Саудовская Аравия',
    tr: 'Suudi Arabistan',
    zh: '沙特阿拉伯',
  },
  mt: {
    en: 'Malta',
    ar: 'مالطا',
    az: 'Malta',
    de: 'Malta',
    es: 'Malta',
    fa: 'مالت',
    fr: 'Malte',
    id: 'Malta',
    it: 'Malta',
    kk: 'Мальта',
    ko: '몰타',
    ky: 'Мальта',
    ms: 'Malta',
    ru: 'Мальта',
    tr: 'Malta',
    zh: '馬耳他',
  },
  cy: {
    en: 'Cyprus',
    ar: 'قبرص',
    az: 'Kipr Respublikası',
    de: 'Zypern',
    es: 'Chipre',
    fa: 'قبرس',
    fr: 'Chypre',
    id: 'Siprus',
    it: 'Cipro',
    kk: 'Кипр',
    ko: '키프로스',
    ky: 'Кипр',
    ms: 'Cyprus',
    ru: 'Кипр',
    tr: 'Kıbrıs',
    zh: '塞浦路斯',
  },
  id: {
    en: 'Indonesia',
    ar: 'إندونيسيا',
    az: 'İndoneziya',
    de: 'Indonesien',
    es: 'Indonesia',
    fa: 'اندونزی',
    fr: 'Indonésie',
    id: 'Indonesia',
    it: 'Indonesia',
    kk: 'Индонезия',
    ko: '인도네시아',
    ky: 'Индонезия',
    ms: 'Indonesia',
    ru: 'Индонезия',
    tr: 'Endonezya',
    zh: '印度尼西亚',
  },
  bh: {
    en: 'Bahrain',
    ar: 'البحرين',
    az: 'Bəhreyn',
    de: 'Bahrain',
    es: 'Baréin',
    fa: 'بحرین',
    fr: 'Bahreïn',
    id: 'Bahrain',
    it: 'Bahrein',
    kk: 'Бахрейн',
    ko: '바레인',
    ky: 'Бахрейн',
    ms: 'Bahrain',
    ru: 'Бахрейн',
    tr: 'Bahreyn',
    zh: '巴林',
  },
  sy: {
    en: 'Syrian Arab Republic',
    ar: 'سوريا',
    az: 'Suriya',
    de: 'Syrien',
    es: 'Siria',
    fa: 'سوریه',
    fr: 'Syrie',
    id: 'Suriah',
    it: 'Siria',
    kk: 'Сирия',
    ko: '시리아',
    ky: 'Сирия',
    ms: 'Syria',
    ru: 'Сирия',
    tr: 'Suriye',
    zh: '敘利亞',
  },
  lb: {
    en: 'Lebanon',
    ar: 'لبنان',
    az: 'Livan',
    de: 'Libanon',
    es: 'Líbano',
    fa: 'لبنان',
    fr: 'Liban',
    id: 'Lebanon',
    it: 'Libano',
    kk: 'Ливан',
    ko: '레바논',
    ky: 'Ливан',
    ms: 'Lubnan',
    ru: 'Ливан',
    tr: 'Lübnan',
    zh: '黎巴嫩',
  },
  ax: {
    en: 'Aland Islands',
    ar: 'جزر أولاند',
    az: 'Aland adaları',
    de: 'Åland',
    es: 'Åland',
    fa: 'جزایر الند',
    fr: 'Åland',
    id: 'Kepulauan Åland',
    it: 'Isole Åland',
    kk: 'Аланд аралдары',
    ko: '올란드 제도',
    ky: 'Аланд аралдары',
    ms: 'Åland',
    ru: 'Аландские острова',
    tr: 'Åland',
    zh: '奥兰',
  },
  zm: {
    en: 'Zambia',
    ar: 'زامبيا',
    az: 'Zambiya',
    de: 'Sambia',
    es: 'Zambia',
    fa: 'زامبیا',
    fr: 'Zambie',
    id: 'Zambia',
    it: 'Zambia',
    kk: 'Замбия',
    ko: '잠비아',
    ky: 'Замбия',
    ms: 'Zambia',
    ru: 'Замбия',
    tr: 'Zambiya',
    zh: '贊比亞',
  },
  lt: {
    en: 'Lithuania',
    ar: 'ليتوانيا',
    az: 'Litva',
    de: 'Litauen',
    es: 'Lituania',
    fa: 'لیتوانی',
    fr: 'Lituanie',
    id: 'Lithuania',
    it: 'Lituania',
    kk: 'Литва',
    ko: '리투아니아',
    ky: 'Литва',
    ms: 'Lithuania',
    ru: 'Литва',
    tr: 'Litvanya',
    zh: '立陶宛',
  },
  om: {
    en: 'Oman',
    ar: 'سلطنة عمان',
    az: 'Oman',
    de: 'Oman',
    es: 'Omán',
    fa: 'عمان',
    fr: 'Oman',
    id: 'Oman',
    it: 'Oman',
    kk: 'Оман',
    ko: '오만',
    ky: 'Оман',
    ms: 'Oman',
    ru: 'Оман',
    tr: 'Umman',
    zh: '阿曼',
  },
  rs: {
    en: 'Serbia',
    ar: 'صربيا',
    az: 'Serbiya',
    de: 'Serbien',
    es: 'Serbia',
    fa: 'صربستان',
    fr: 'Serbie',
    id: 'Serbia',
    it: 'Serbia',
    kk: 'Сербия',
    ko: '세르비아',
    ky: 'Сербия',
    ms: 'Serbia',
    ru: 'Сербия',
    tr: 'Sırbistan',
    zh: '塞爾維亞',
  },
  si: {
    en: 'Slovenia',
    ar: 'سلوفينيا',
    az: 'Sloveniya',
    de: 'Slowenien',
    es: 'Eslovenia',
    fa: 'اسلوونی',
    fr: 'Slovénie',
    id: 'Slovenia',
    it: 'Slovenia',
    kk: 'Словения',
    ko: '슬로베니아',
    ky: 'Словения',
    ms: 'Slovenia',
    ru: 'Словения',
    tr: 'Slovenya',
    zh: '斯洛文尼亞',
  },
  mk: {
    en: 'North Macedonia',
    ar: 'مقدونيا الشمالية',
    az: 'Şimali Makedoniya',
    de: 'Nordmazedonien',
    es: 'Macedonia del Norte',
    fa: 'مقدونیه شمالی',
    fr: 'Macédoine du Nord',
    id: 'Makedonia Utara',
    it: 'Macedonia del Nord',
    kk: 'Солтүстік Македония',
    ko: '북마케도니아',
    ky: 'Түндүк Македония',
    ms: 'Macedonia Utara',
    ru: 'Северная Македония',
    tr: 'Kuzey Makedonya',
    zh: '北马其顿',
  },
  li: {
    en: 'Liechtenstein',
    ar: 'ليختنشتاين',
    az: 'Lixtenşteyn',
    de: 'Liechtenstein',
    es: 'Liechtenstein',
    fa: 'لیختناشتاین',
    fr: 'Liechtenstein',
    id: 'Liechtenstein',
    it: 'Liechtenstein',
    kk: 'Лихтенштейн',
    ko: '리히텐슈타인',
    ky: 'Лихтенштейн',
    ms: 'Liechtenstein',
    ru: 'Лихтенштейн',
    tr: 'Lihtenştayn',
    zh: '列支敦斯登',
  },
  je: {
    en: 'Jersey',
    ar: 'جيرزي',
    az: 'Cersi',
    de: 'Jersey',
    es: 'Jersey',
    fa: 'جرزی',
    fr: 'Jersey',
    id: 'Jersey',
    it: 'Jersey',
    kk: 'Джерси',
    ko: '저지섬',
    ky: 'Жерси',
    ms: 'Jersey',
    ru: 'Джерси',
    tr: 'Jersey',
    zh: '澤西',
  },
  ba: {
    en: 'Bosnia and Herzegovina',
    ar: 'البوسنة والهرسك',
    az: 'Bosniya və Herseqovina',
    de: 'Bosnien und Herzegowina',
    es: 'Bosnia y Herzegovina',
    fa: 'بوسنی و هرزگوین',
    fr: 'Bosnie-Herzégovine',
    id: 'Bosnia dan Herzegovina',
    it: 'Bosnia ed Erzegovina',
    kk: 'Босния және Герцеговина',
    ko: '보스니아 헤르체고비나',
    ky: 'Босния жана Герцеговина',
    ms: 'Bosnia dan Herzegovina',
    ru: 'Босния и Герцеговина',
    tr: 'Bosna-Hersek',
    zh: '波斯尼亚和黑塞哥维那',
  },
  az: {
    en: 'Azerbaijan',
    ar: 'أذربيجان',
    az: 'Azərbaycan',
    de: 'Aserbaidschan',
    es: 'Azerbaiyán',
    fa: 'جمهوری آذربایجان',
    fr: 'Azerbaïdjan',
    id: 'Azerbaijan',
    it: 'Azerbaigian',
    kk: 'Әзірбайжан',
    ko: '아제르바이잔',
    ky: 'Азербайжан',
    ms: 'Azerbaijan',
    ru: 'Азербайджан',
    tr: 'Azerbaycan',
    zh: '阿塞拜疆',
  },
  kg: {
    en: 'Kyrgyzstan',
    ar: 'قيرغيزستان',
    az: 'Qırğızıstan',
    de: 'Kirgisistan',
    es: 'Kirguistán',
    fa: 'قرقیزستان',
    fr: 'Kirghizistan',
    id: 'Kirgizstan',
    it: 'Kirghizistan',
    kk: 'Қырғызстан',
    ko: '키르기스스탄',
    ky: 'Кыргызстан',
    ms: 'Kyrgyzstan',
    ru: 'Кыргызстан',
    tr: 'Kırgızistan',
    zh: '吉尔吉斯斯坦',
  },
  im: {
    en: 'Isle of Man',
    ar: 'جزيرة مان',
    az: 'Men adası',
    de: 'Isle of Man',
    es: 'Isla de Man',
    fa: 'جزیره من',
    fr: 'Île de Man',
    id: 'Isle of Man',
    it: 'isola di Man',
    kk: 'Мән аралы',
    ko: '맨섬',
    ky: 'Мэн аралы',
    ms: 'Isle of Man',
    ru: 'Остров Мэн',
    tr: 'Man Adası',
    zh: '马恩岛',
  },
  gi: {
    en: 'Gibraltar',
    ar: 'جبل طارق',
    az: 'Cəbəllüttariq',
    de: 'Gibraltar',
    es: 'Gibraltar',
    fa: 'جبل طارق',
    fr: 'Gibraltar',
    id: 'Gibraltar',
    it: 'Gibilterra',
    kk: 'Гибралтар',
    ko: '지브롤터',
    ky: 'Гибралтар',
    ms: 'Gibraltar',
    ru: 'Гибралтар',
    tr: 'Cebelitarık',
    zh: '直布羅陀',
  },
  ly: {
    en: 'Libya',
    ar: 'ليبيا',
    az: 'Liviya',
    de: 'Libyen',
    es: 'Libia',
    fa: 'لیبی',
    fr: 'Libye',
    id: 'Libya',
    it: 'Libia',
    kk: 'Ливия',
    ko: '리비아',
    ky: 'Ливия',
    ms: 'Libya',
    ru: 'Ливия',
    tr: 'Libya',
    zh: '利比亞',
  },
  ye: {
    en: 'Yemen',
    ar: 'اليمن',
    az: 'Yəmən',
    de: 'Jemen',
    es: 'Yemen',
    fa: 'یمن',
    fr: 'Yémen',
    id: 'Yaman',
    it: 'Yemen',
    kk: 'Йемен',
    ko: '예멘',
    ky: 'Йемен',
    ms: 'Yaman',
    ru: 'Йемен',
    tr: 'Yemen',
    zh: '也门',
  },
  by: {
    en: 'Belarus',
    ar: 'بيلاروس',
    az: 'Belarus',
    de: 'Belarus',
    es: 'Bielorrusia',
    fa: 'بلاروس',
    fr: 'Biélorussie',
    id: 'Belarus',
    it: 'Bielorussia',
    kk: 'Беларусь',
    ko: '벨라루스',
    ky: 'Беларусь',
    ms: 'Belarus',
    ru: 'Белоруссия',
    tr: 'Beyaz Rusya',
    zh: '白俄羅斯',
  },
  uz: {
    en: 'Uzbekistan',
    ar: 'أوزبكستان',
    az: 'Özbəkistan',
    de: 'Usbekistan',
    es: 'Uzbekistán',
    fa: 'ازبکستان',
    fr: 'Ouzbékistan',
    id: 'Uzbekistan',
    it: 'Uzbekistan',
    kk: 'Өзбекстан',
    ko: '우즈베키스탄',
    ky: 'Өзбекстан',
    ms: 'Uzbekistan',
    ru: 'Узбекистан',
    tr: 'Özbekistan',
    zh: '烏茲別克',
  },
  yt: {
    en: 'Mayotte',
    ar: 'مايوت',
    az: 'Mayotta',
    de: 'Mayotte',
    es: 'Mayotte',
    fa: 'مایوت',
    fr: 'Mayotte',
    id: 'Mayotte',
    it: 'Mayotte',
    kk: 'Майотт',
    ko: '마요트',
    ky: 'Майотта',
    ms: 'Mayotte',
    ru: 'Майотта',
    tr: 'Mayotte',
    zh: '马约特',
  },
  mq: {
    en: 'Martinique',
    ar: 'مارتينيك',
    az: 'Martinika',
    de: 'Martinique',
    es: 'Martinica',
    fa: 'مارتینیک',
    fr: 'Martinique',
    id: 'Pulau Martinik',
    it: 'Martinica',
    kk: 'Мартиника',
    ko: '마르티니크',
    ky: 'Мартиника',
    ms: 'Martinique',
    ru: 'Мартиника',
    tr: 'Martinique',
    zh: '馬提尼克',
  },
  gp: {
    en: 'Guadeloupe',
    ar: 'غوادلوب',
    az: 'Qvadelupa',
    de: 'Guadeloupe',
    es: 'Guadalupe',
    fa: 'جزیره گوادلوپ',
    fr: 'Guadeloupe',
    id: 'Guadeloupe',
    it: 'Guadalupa',
    kk: 'Гваделупа',
    ko: '과들루프',
    ky: 'Гваделупа',
    ms: 'Guadeloupe',
    ru: 'Гваделупа',
    tr: 'Guadeloupe',
    zh: '瓜德羅普',
  },
  gf: {
    en: 'French Guiana',
    ar: 'غويانا الفرنسية',
    az: 'Fransa Qvianası',
    de: 'Französisch-Guayana',
    es: 'Guayana Francesa',
    fa: 'گویان فرانسه',
    fr: 'Guyane',
    id: 'Guyana Prancis',
    it: 'Guyana francese',
    kk: 'Француз Гвианасы',
    ko: '프랑스령 기아나',
    ky: 'Гвиана',
    ms: 'Guiana Perancis',
    ru: 'Французская Гвиана',
    tr: 'French Guiana',
    zh: '法屬圭亞那',
  },
  nz: {
    en: 'New Zealand',
    ar: 'نيوزيلندا',
    az: 'Yeni Zelandiya',
    de: 'Neuseeland',
    es: 'Nueva Zelanda',
    fa: 'نیوزیلند',
    fr: 'Nouvelle-Zélande',
    id: 'Selandia Baru',
    it: 'Nuova Zelanda',
    kk: 'Жаңа Зеландия',
    ko: '뉴질랜드',
    ky: 'Жаңы Зеландия',
    ms: 'New Zealand',
    ru: 'Новая Зеландия',
    tr: 'Yeni Zelanda',
    zh: '新西兰',
  },
  lk: {
    en: 'Sri Lanka',
    ar: 'سريلانكا',
    az: 'Şri-Lanka',
    de: 'Sri Lanka',
    es: 'Sri Lanka',
    fa: 'سریلانکا',
    fr: 'Sri Lanka',
    id: 'Sri Lanka',
    it: 'Sri Lanka',
    kk: 'Шри-Ланка',
    ko: '스리랑카',
    ky: 'Шри-Ланка',
    ms: 'Sri Lanka',
    ru: 'Шри-Ланка',
    tr: 'Sri Lanka',
    zh: '斯里蘭卡',
  },
  sz: {
    en: 'Eswatini',
    ar: 'إسواتيني',
    az: 'Esvatini',
    de: 'Eswatini',
    es: 'Esuatini',
    fa: 'اسواتینی',
    fr: 'Eswatini',
    id: 'Eswatini',
    it: 'Eswatini',
    kk: 'Эсватини',
    ko: '에스와티니',
    ky: 'Эсватини',
    ms: 'Eswatini',
    ru: 'Эсватини',
    tr: 'Esvatini',
    zh: '斯威士兰',
  },
  bd: {
    en: 'Bangladesh',
    ar: 'بنغلاديش',
    az: 'Banqladeş',
    de: 'Bangladesch',
    es: 'Bangladés',
    fa: 'بنگلادش',
    fr: 'Bangladesh',
    id: 'Bangladesh',
    it: 'Bangladesh',
    kk: 'Бангладеш',
    ko: '방글라데시',
    ky: 'Баңгладеш',
    ms: 'Bangladesh',
    ru: 'Бангладеш',
    tr: 'Bangladeş',
    zh: '孟加拉國',
  },
  kw: {
    en: 'Kuwait',
    ar: 'الكويت',
    az: 'Küveyt',
    de: 'Kuwait',
    es: 'Kuwait',
    fa: 'کویت',
    fr: 'Koweït',
    id: 'Kuwait',
    it: 'Kuwait',
    kk: 'Кувейт',
    ko: '쿠웨이트',
    ky: 'Кувейт',
    ms: 'Kuwait',
    ru: 'Кувейт',
    tr: 'Kuveyt',
    zh: '科威特',
  },
  bt: {
    en: 'Bhutan',
    ar: 'بوتان',
    az: 'Butan',
    de: 'Bhutan',
    es: 'Bután',
    fa: 'بوتان',
    fr: 'Bhoutan',
    id: 'Bhutan',
    it: 'Bhutan',
    kk: 'Бутан Патшалығы',
    ko: '부탄',
    ky: 'Бутан',
    ms: 'Bhutan',
    ru: 'Бутан',
    tr: 'Bhutan',
    zh: '不丹',
  },
  bn: {
    en: 'Brunei Darussalam',
    ar: 'بروناي دار السلام',
    az: 'Bruney Darussalam',
    de: 'Brunei Darussalam',
    es: 'Brunéi Darussalam',
    fa: 'برونئی دارالسلام',
    fr: 'Brunei Darussalam',
    id: 'Brunei Darussalam',
    it: 'Brunei Darussalam',
    kk: 'Бруней-Даруссалам',
    ko: '브루나이 다루살람',
    ky: 'Бруней-Даруссалам',
    ms: 'Brunei Darussalam',
    ru: 'Бруней-Даруссалам',
    tr: 'Brunei Sultanlığı',
    zh: '文莱达鲁萨兰国',
  },
  pm: {
    en: 'Saint Pierre and Miquelon',
    ar: 'سان بيير وميكلون',
    az: 'Sent Pyer və Mikelon',
    de: 'Saint-Pierre und Miquelon',
    es: 'San Pedro y Miquelón',
    fa: 'سن پیر و میکلن',
    fr: 'Saint-Pierre-et-Miquelon',
    id: 'Saint Pierre dan Miquelon',
    it: 'Saint-Pierre e Miquelon',
    kk: 'Сен-Пьер және Микелон',
    ko: '생피에르 미클롱',
    ky: 'Сенпьер жана Микелон',
    ms: 'Saint Pierre dan Miquelon',
    ru: 'Сен-Пьер и Микелон',
    tr: 'Saint Pierre and Miquelon',
    zh: '圣皮埃尔和密克隆',
  },
  pa: {
    en: 'Panama',
    ar: 'بنما',
    az: 'Panama',
    de: 'Panama',
    es: 'Panamá',
    fa: 'پاناما',
    fr: 'Panama',
    id: 'Panama',
    it: 'Panama',
    kk: 'Панама',
    ko: '파나마',
    ky: 'Панама',
    ms: 'Panama',
    ru: 'Панама',
    tr: 'Panama',
    zh: '巴拿馬',
  },
  la: {
    en: "Lao People's Democratic Republic",
    ar: 'لاوس',
    az: 'Laos',
    de: 'Laos',
    es: 'Laos',
    fa: 'لائوس',
    fr: 'Laos',
    id: 'Laos',
    it: 'Laos',
    kk: 'Лаос',
    ko: '라오스',
    ky: 'Лаос',
    ms: 'Laos',
    ru: 'Лаос',
    tr: 'Laos',
    zh: '老撾',
  },
  gu: {
    en: 'Guam',
    ar: 'غوام',
    az: 'Quam',
    de: 'Guam',
    es: 'Guam',
    fa: 'گوآم',
    fr: 'Guam',
    id: 'Guam',
    it: 'Guam',
    kk: 'Гуам',
    ko: '괌',
    ky: 'Гуам',
    ms: 'Guam',
    ru: 'Гуам',
    tr: 'Guam',
    zh: '關島',
  },
  mp: {
    en: 'Northern Mariana Islands',
    ar: 'جزر ماريانا الشمالية',
    az: 'Şimali Marian adaları',
    de: 'Nördliche Marianen',
    es: 'Islas Marianas del Norte',
    fa: 'جزایر ماریانای شمالی',
    fr: 'îles Mariannes du Nord',
    id: 'Kepulauan Mariana Utara',
    it: 'Isole Marianne Settentrionali',
    kk: 'Солтүстік Мариана аралдары',
    ko: '북마리아나 제도',
    ky: 'Түндүк мариана аралдары',
    ms: 'Kepulauan Mariana Utara',
    ru: 'Северные Марианские Острова',
    tr: 'Kuzey Mariana Adaları',
    zh: '北马里亚纳群岛',
  },
  do: {
    en: 'Dominican Republic',
    ar: 'جمهورية الدومينيكان',
    az: 'Dominikan Respublikası',
    de: 'Dominikanische Republik',
    es: 'República Dominicana',
    fa: 'جمهوری دومینیکن',
    fr: 'République dominicaine',
    id: 'Republik Dominika',
    it: 'Repubblica Dominicana',
    kk: 'Доминикан Республикасы',
    ko: '도미니카 공화국',
    ky: 'Доминикана Республикасы',
    ms: 'Republik Dominika',
    ru: 'Доминиканская Республика',
    tr: 'Dominik Cumhuriyeti',
    zh: '多明尼加',
  },
  ng: {
    en: 'Nigeria',
    ar: 'نيجيريا',
    az: 'Nigeriya',
    de: 'Nigeria',
    es: 'Nigeria',
    fa: 'نیجریه',
    fr: 'Nigeria',
    id: 'Nigeria',
    it: 'Nigeria',
    kk: 'Нигерия',
    ko: '나이지리아',
    ky: 'Нигерия',
    ms: 'Nigeria',
    ru: 'Нигерия',
    tr: 'Nijerya',
    zh: '奈及利亞',
  },
  ec: {
    en: 'Ecuador',
    ar: 'الإكوادور',
    az: 'Ekvador',
    de: 'Ecuador',
    es: 'Ecuador',
    fa: 'اکوادور',
    fr: 'Équateur',
    id: 'Ekuador',
    it: 'Ecuador',
    kk: 'Эквадор',
    ko: '에콰도르',
    ky: 'Эквадор',
    ms: 'Ecuador',
    ru: 'Эквадор',
    tr: 'Ekvador',
    zh: '厄瓜多尔',
  },
  cr: {
    en: 'Costa Rica',
    ar: 'كوستاريكا',
    az: 'Kosta-Rika',
    de: 'Costa Rica',
    es: 'Costa Rica',
    fa: 'کاستاریکا',
    fr: 'Costa Rica',
    id: 'Kosta Rika',
    it: 'Costa Rica',
    kk: 'Коста-Рика',
    ko: '코스타리카',
    ky: 'Коста-Рика',
    ms: 'Costa Rica',
    ru: 'Коста-Рика',
    tr: 'Kosta Rika',
    zh: '哥斯达黎加',
  },
  pr: {
    en: 'Puerto Rico',
    ar: 'بورتوريكو',
    az: 'Puerto Riko',
    de: 'Puerto Rico',
    es: 'Puerto Rico',
    fa: 'پورتوریکو',
    fr: 'Porto Rico',
    id: 'Puerto Riko',
    it: 'Porto Rico',
    kk: 'Пуэрто-Рико',
    ko: '푸에르토리코',
    ky: 'Пуэрто-Рико',
    ms: 'Puerto Rico',
    ru: 'Пуэрто-Рико',
    tr: 'Porto Riko',
    zh: '波多黎各',
  },
  bo: {
    en: 'Bolivia (Plurinational State of)',
    ar: 'بوليفيا',
    az: 'Boliviya',
    de: 'Bolivien',
    es: 'Bolivia',
    fa: 'بولیوی',
    fr: 'Bolivie',
    id: 'Bolivia',
    it: 'Bolivia',
    kk: 'Боливия',
    ko: '볼리비아',
    ky: 'Боливия',
    ms: 'Bolivia',
    ru: 'Боливия',
    tr: 'Bolivya',
    zh: '玻利維亞',
  },
  cx: {
    en: 'Christmas Island',
    ar: 'جزيرة عيد الميلاد',
    az: 'Milad adası',
    de: 'Weihnachtsinsel',
    es: 'Isla de Navidad',
    fa: 'جزیره کریسمس',
    fr: 'île Christmas',
    id: 'Pulau Natal',
    it: 'Isola di Natale',
    kk: 'Кристмас аралы',
    ko: '크리스마스섬',
    ky: 'Рождество аралы',
    ms: 'Pulau Krismas',
    ru: 'Остров Рождества',
    tr: 'Christmas Adası (I)',
    zh: '聖誕島',
  },
  mv: {
    en: 'Maldives',
    ar: 'المالديف',
    az: 'Maldiv adaları',
    de: 'Malediven',
    es: 'Maldivas',
    fa: 'مالدیو',
    fr: 'Maldives',
    id: 'Maladewa',
    it: 'Maldive',
    kk: 'Мальдив Республикасы',
    ko: '몰디브',
    ky: 'Мальдивдер',
    ms: 'Maldives',
    ru: 'Мальдивы',
    tr: 'Maldivler',
    zh: '馬爾代夫',
  },
  pk: {
    en: 'Pakistan',
    ar: 'باكستان',
    az: 'Pakistan',
    de: 'Pakistan',
    es: 'Pakistán',
    fa: 'پاکستان',
    fr: 'Pakistan',
    id: 'Pakistan',
    it: 'Pakistan',
    kk: 'Пәкістан',
    ko: '파키스탄',
    ky: 'Пакистан',
    ms: 'Pakistan',
    ru: 'Пакистан',
    tr: 'Pakistan',
    zh: '巴基斯坦',
  },
  mn: {
    en: 'Mongolia',
    ar: 'منغوليا',
    az: 'Monqolustan',
    de: 'Mongolei',
    es: 'Mongolia',
    fa: 'مغولستان',
    fr: 'Mongolie',
    id: 'Mongolia',
    it: 'Mongolia',
    kk: 'Моңғолия',
    ko: '몽골',
    ky: 'Моңголстан',
    ms: 'Mongolia',
    ru: 'Монголия',
    tr: 'Moğolistan',
    zh: '蒙古國',
  },
  nf: {
    en: 'Norfolk Island',
    ar: 'جزيرة نورفولك',
    az: 'Norfolk adası',
    de: 'Norfolkinsel',
    es: 'Isla Norfolk',
    fa: 'جزیره نورفک',
    fr: 'île Norfolk',
    id: 'Pulau Norfolk',
    it: 'Isola Norfolk',
    kk: 'Норфолк',
    ko: '노퍽섬',
    ky: 'Норфолк аралы',
    ms: 'Pulau Norfolk',
    ru: 'Норфолк',
    tr: 'Norfolk Adası',
    zh: '诺福克岛',
  },
  pg: {
    en: 'Papua New Guinea',
    ar: 'بابوا غينيا الجديدة',
    az: 'Papua-Yeni Qvineya',
    de: 'Papua-Neuguinea',
    es: 'Papúa Nueva Guinea',
    fa: 'پاپوآ گینه نو',
    fr: 'Papouasie-Nouvelle-Guinée',
    id: 'Papua Nugini',
    it: 'Papua Nuova Guinea',
    kk: 'Папуа Жаңа Гвинея',
    ko: '파푸아뉴기니',
    ky: 'Папуа-Жаӊы-Гвинея.',
    ms: 'Papua New Guinea',
    ru: 'Папуа — Новая Гвинея',
    tr: 'Papua Yeni Gine',
    zh: '巴布亚新几内亚',
  },
  tl: {
    en: 'Timor-Leste',
    ar: 'تيمور الشرقية',
    az: 'Şərqi Timor',
    de: 'Osttimor',
    es: 'Timor Oriental',
    fa: 'تیمور شرقی',
    fr: 'Timor oriental',
    id: 'Timor Leste',
    it: 'Timor Est',
    kk: 'Тимор-Лесте',
    ko: '동티모르',
    ky: 'Тимор Лешти',
    ms: 'Timor Leste',
    ru: 'Восточный Тимор',
    tr: 'Doğu Timor',
    zh: '東帝汶',
  },
  sb: {
    en: 'Solomon Islands',
    ar: 'جزر سليمان',
    az: 'Solomon adaları',
    de: 'Salomonen',
    es: 'Islas Salomón',
    fa: 'جزایر سلیمان',
    fr: 'Îles Salomon',
    id: 'Kepulauan Solomon',
    it: 'Isole Salomone',
    kk: 'Сүлеймен аралдары',
    ko: '솔로몬 제도',
    ky: 'Соломон Аралдары',
    ms: 'Kepulauan Solomon',
    ru: 'Соломоновы Острова',
    tr: 'Solomon Adaları',
    zh: '所罗门群岛',
  },
  vu: {
    en: 'Vanuatu',
    ar: 'فانواتو',
    az: 'Vanuatu',
    de: 'Vanuatu',
    es: 'Vanuatu',
    fa: 'وانواتو',
    fr: 'Vanuatu',
    id: 'Vanuatu',
    it: 'Vanuatu',
    kk: 'Вануату',
    ko: '바누아투',
    ky: 'Вануату',
    ms: 'Vanuatu',
    ru: 'Вануату',
    tr: 'Vanuatu',
    zh: '萬那杜',
  },
  fj: {
    en: 'Fiji',
    ar: 'فيجي',
    az: 'Fici',
    de: 'Fidschi',
    es: 'Fiyi',
    fa: 'فیجی',
    fr: 'Fidji',
    id: 'Fiji',
    it: 'Figi',
    kk: 'Фиджи',
    ko: '피지',
    ky: 'Фижи',
    ms: 'Fiji',
    ru: 'Фиджи',
    tr: 'Fiji',
    zh: '斐濟',
  },
  ck: {
    en: 'Cook Islands',
    ar: 'جزر كوك',
    az: 'Kuk adaları',
    de: 'Cookinseln',
    es: 'Islas Cook',
    fa: 'جزایر کوک',
    fr: 'Îles Cook',
    id: 'Kepulauan Cook',
    it: 'Isole Cook',
    kk: 'Кук аралдары',
    ko: '쿡 제도',
    ky: 'Кук аралдары',
    ms: 'Kepulauan Cook',
    ru: 'Острова Кука',
    tr: 'Cook Adaları',
    zh: '库克群岛',
  },
  to: {
    en: 'Tonga',
    ar: 'تونغا',
    az: 'Tonqa',
    de: 'Tonga',
    es: 'Tonga',
    fa: 'تونگا',
    fr: 'Tonga',
    id: 'Tonga',
    it: 'Tonga',
    kk: 'Тонга',
    ko: '통가',
    ky: 'Тонга',
    ms: 'Tonga',
    ru: 'Тонга',
    tr: 'Tonga',
    zh: '東加',
  },
  np: {
    en: 'Nepal',
    ar: 'نيبال',
    az: 'Nepal',
    de: 'Nepal',
    es: 'Nepal',
    fa: 'نپال',
    fr: 'Népal',
    id: 'Nepal',
    it: 'Nepal',
    kk: 'Непал',
    ko: '네팔',
    ky: 'Непал',
    ms: 'Nepal',
    ru: 'Непал',
    tr: 'Nepal',
    zh: '尼泊爾',
  },
  ni: {
    en: 'Nicaragua',
    ar: 'نيكاراغوا',
    az: 'Nikaraqua',
    de: 'Nicaragua',
    es: 'Nicaragua',
    fa: 'نیکاراگوئه',
    fr: 'Nicaragua',
    id: 'Nikaragua',
    it: 'Nicaragua',
    kk: 'Никарагуа',
    ko: '니카라과',
    ky: 'Никарагуа',
    ms: 'Nicaragua',
    ru: 'Никарагуа',
    tr: 'Nikaragua',
    zh: '尼加拉瓜',
  },
  jm: {
    en: 'Jamaica',
    ar: 'جامايكا',
    az: 'Yamayka',
    de: 'Jamaika',
    es: 'Jamaica',
    fa: 'جامائیکا',
    fr: 'Jamaïque',
    id: 'Jamaika',
    it: 'Giamaica',
    kk: 'Ямайка',
    ko: '자메이카',
    ky: 'Ямайка',
    ms: 'Jamaica',
    ru: 'Ямайка',
    tr: 'Jamaika',
    zh: '牙買加',
  },
  al: {
    en: 'Albania',
    ar: 'ألبانيا',
    az: 'Albaniya',
    de: 'Albanien',
    es: 'Albania',
    fa: 'آلبانی',
    fr: 'Albanie',
    id: 'Albania',
    it: 'Albania',
    kk: 'Албания',
    ko: '알바니아',
    ky: 'Албания',
    ms: 'Albania',
    ru: 'Албания',
    tr: 'Arnavutluk',
    zh: '阿爾巴尼亞',
  },
  zw: {
    en: 'Zimbabwe',
    ar: 'زيمبابوي',
    az: 'Zimbabve',
    de: 'Simbabwe',
    es: 'Zimbabue',
    fa: 'زیمبابوه',
    fr: 'Zimbabwe',
    id: 'Zimbabwe',
    it: 'Zimbabwe',
    kk: 'Зимбабве',
    ko: '짐바브웨',
    ky: 'Зимбабве',
    ms: 'Zimbabwe',
    ru: 'Зимбабве',
    tr: 'Zimbabve',
    zh: '津巴布韦',
  },
  tt: {
    en: 'Trinidad and Tobago',
    ar: 'ترينيداد وتوباغو',
    az: 'Trinidad və Tobaqo',
    de: 'Trinidad und Tobago',
    es: 'Trinidad y Tobago',
    fa: 'ترینیداد و توباگو',
    fr: 'Trinité-et-Tobago',
    id: 'Trinidad dan Tobago',
    it: 'Trinidad e Tobago',
    kk: 'Тринидад және Тобаго',
    ko: '트리니다드 토바고',
    ky: 'Тринидад жана Тобаго',
    ms: 'Trinidad dan Tobago',
    ru: 'Тринидад и Тобаго',
    tr: 'Trinidad ve Tobago',
    zh: '千里達及托巴哥',
  },
  cu: {
    en: 'Cuba',
    ar: 'كوبا',
    az: 'Kuba',
    de: 'Kuba',
    es: 'Cuba',
    fa: 'کوبا',
    fr: 'Cuba',
    id: 'Kuba',
    it: 'Cuba',
    kk: 'Куба',
    ko: '쿠바',
    ky: 'Куба',
    ms: 'Cuba',
    ru: 'Куба',
    tr: 'Küba',
    zh: '古巴',
  },
  ss: {
    en: 'South Sudan',
    ar: 'جنوب السودان',
    az: 'Cənubi Sudan',
    de: 'Südsudan',
    es: 'Sudán del Sur',
    fa: 'سودان جنوبی',
    fr: 'Soudan du Sud',
    id: 'Sudan Selatan',
    it: 'Sudan del Sud',
    kk: 'Оңтүстік Судан',
    ko: '남수단',
    ky: 'Түштүк Судан',
    ms: 'Sudan Selatan',
    ru: 'Южный Судан',
    tr: 'Güney Sudan',
    zh: '南蘇丹',
  },
  af: {
    en: 'Afghanistan',
    ar: 'أفغانستان',
    az: 'Əfqanıstan',
    de: 'Afghanistan',
    es: 'Afganistán',
    fa: 'افغانستان',
    fr: 'Afghanistan',
    id: 'Afghanistan',
    it: 'Afghanistan',
    kk: 'Ауғанстан',
    ko: '아프가니스탄',
    ky: 'Ооганстан',
    ms: 'Afghanistan',
    ru: 'Афганистан',
    tr: 'Afganistan',
    zh: '阿富汗',
  },
  gd: {
    en: 'Grenada',
    ar: 'غرينادا',
    az: 'Qrenada',
    de: 'Grenada',
    es: 'Granada',
    fa: 'گرنادا',
    fr: 'Grenade',
    id: 'Grenada',
    it: 'Grenada',
    kk: 'Гренада',
    ko: '그레나다',
    ky: 'Гренада',
    ms: 'Grenada',
    ru: 'Гренада',
    tr: 'Grenada',
    zh: '格瑞那達',
  },
  kn: {
    en: 'Saint Kitts and Nevis',
    ar: 'سانت كيتس ونيفيس',
    az: 'Sent-Kits və Nevis',
    de: 'St. Kitts und Nevis',
    es: 'San Cristóbal y Nieves',
    fa: 'سنت کیتس و نویس',
    fr: 'Saint-Christophe-et-Niévès',
    id: 'Saint Kitts dan Nevis',
    it: 'Saint Kitts e Nevis',
    kk: 'Сент-Киттс және Невис',
    ko: '세인트키츠 네비스',
    ky: 'Сент-Китс жана Невис',
    ms: 'Santo Kitts dan Nevis',
    ru: 'Сент-Китс и Невис',
    tr: 'Saint Kitts ve Nevis',
    zh: '聖克里斯多福及尼維斯',
  },
  ag: {
    en: 'Antigua and Barbuda',
    ar: 'أنتيغوا وباربودا',
    az: 'Antiqua və Barbuda',
    de: 'Antigua und Barbuda',
    es: 'Antigua y Barbuda',
    fa: 'آنتیگوا و باربودا',
    fr: 'Antigua-et-Barbuda',
    id: 'Antigua dan Barbuda',
    it: 'Antigua e Barbuda',
    kk: 'Антигуа және Барбуда',
    ko: '앤티가 바부다',
    ky: 'Антигуа жана Барбуда',
    ms: 'Antigua dan Barbuda',
    ru: 'Антигуа и Барбуда',
    tr: 'Antigua ve Barbuda',
    zh: '安提瓜和巴布达',
  },
  mh: {
    en: 'Marshall Islands',
    ar: 'جزر مارشال',
    az: 'Marşall adaları',
    de: 'Marshallinseln',
    es: 'Islas Marshall',
    fa: 'جزایر مارشال',
    fr: 'Îles Marshall',
    id: 'Kepulauan Marshall',
    it: 'Isole Marshall',
    kk: 'Маршалл Аралдары Республикасы',
    ko: '마셜 제도',
    ky: 'Маршалл аралдары',
    ms: 'Kepulauan Marshall',
    ru: 'Маршалловы Острова',
    tr: 'Marshall Adaları',
    zh: '馬紹爾群島',
  },
  vc: {
    en: 'Saint Vincent and The Grenadines',
    ar: 'سانت فينسنت والغرينادين',
    az: 'Sent-Vinsent və Qrenadina',
    de: 'St. Vincent und die Grenadinen',
    es: 'San Vicente y las Granadinas',
    fa: 'سنت وینسنت و گرنادینها',
    fr: 'Saint-Vincent-et-les-Grenadines',
    id: 'Saint Vincent dan Grenadines',
    it: 'Saint Vincent e Grenadine',
    kk: 'Сент-Винсент және Гренадиндер',
    ko: '세인트빈센트 그레나딘',
    ky: 'Сент-Винсент жана Гренадиндер',
    ms: 'Saint Vincent dan Grenadines',
    ru: 'Сент-Винсент и Гренадины',
    tr: 'Saint Vincent ve Grenadinler',
    zh: '圣文森特和格林纳丁斯',
  },
  dm: {
    en: 'Dominica',
    ar: 'دومينيكا',
    az: 'Dominika',
    de: 'Dominica',
    es: 'Dominica',
    fa: 'دومینیکا',
    fr: 'Dominique',
    id: 'Dominika',
    it: 'Dominica',
    kk: 'Доминика',
    ko: '도미니카 연방',
    ky: 'Доминика',
    ms: 'Dominika',
    ru: 'Доминика',
    tr: 'Dominika',
    zh: '多米尼克',
  },
  ky: {
    en: 'Cayman Islands',
    ar: 'جزر كايمان',
    az: 'Kayman adaları',
    de: 'Cayman Islands',
    es: 'Islas Caimán',
    fa: 'جزایر کیمن',
    fr: 'îles Caïmans',
    id: 'Kepulauan Cayman',
    it: 'Isole Cayman',
    kk: 'Кайман аралдары',
    ko: '케이맨 제도',
    ky: 'Кайман аралдары',
    ms: 'Kepulauan Cayman',
    ru: 'Острова Кайман',
    tr: 'Cayman Adaları',
    zh: '開曼群島',
  },
  mm: {
    en: 'Myanmar',
    ar: 'ميانمار',
    az: 'Myanma',
    de: 'Myanmar',
    es: 'Birmania',
    fa: 'میانمار',
    fr: 'Birmanie',
    id: 'Myanmar',
    it: 'Birmania',
    kk: 'Мианма',
    ko: '미얀마',
    ky: 'Мьянма',
    ms: 'Myanmar',
    ru: 'Мьянма',
    tr: 'Myanmar',
    zh: '緬甸',
  },
  uy: {
    en: 'Uruguay',
    ar: 'الأوروغواي',
    az: 'Uruqvay',
    de: 'Uruguay',
    es: 'Uruguay',
    fa: 'اروگوئه',
    fr: 'Uruguay',
    id: 'Uruguay',
    it: 'Uruguay',
    kk: 'Уругвай',
    ko: '우루과이',
    ky: 'Уругвай',
    ms: 'Uruguay',
    ru: 'Уругвай',
    tr: 'Uruguay',
    zh: '烏拉圭',
  },
  ma: {
    en: 'Morocco',
    ar: 'المغرب',
    az: 'Mərakeş',
    de: 'Marokko',
    es: 'Marruecos',
    fa: 'مراکش',
    fr: 'Maroc',
    id: 'Maroko',
    it: 'Marocco',
    kk: 'Мағрибия',
    ko: '모로코',
    ky: 'Марокко',
    ms: 'Maghribi',
    ru: 'Марокко',
    tr: 'Fas',
    zh: '摩洛哥',
  },
  me: {
    en: 'Montenegro',
    ar: 'الجبل الأسود',
    az: 'Monteneqro',
    de: 'Montenegro',
    es: 'Montenegro',
    fa: 'مونتهنگرو',
    fr: 'Monténégro',
    id: 'Montenegro',
    it: 'Montenegro',
    kk: 'Черногория',
    ko: '몬테네그로',
    ky: 'Монтенегро',
    ms: 'Montenegro',
    ru: 'Черногория',
    tr: 'Karadağ',
    zh: '蒙特內哥羅',
  },
  mu: {
    en: 'Mauritius',
    ar: 'موريشيوس',
    az: 'Mavriki',
    de: 'Mauritius',
    es: 'Mauricio',
    fa: 'موریس',
    fr: 'Maurice',
    id: 'Mauritius',
    it: 'Mauritius',
    kk: 'Маврикий',
    ko: '모리셔스',
    ky: 'Маврикий',
    ms: 'Mauritius',
    ru: 'Маврикий',
    tr: 'Mauritius',
    zh: '毛里求斯',
  },
  bb: {
    en: 'Barbados',
    ar: 'باربادوس',
    az: 'Barbados',
    de: 'Barbados',
    es: 'Barbados',
    fa: 'باربادوس',
    fr: 'Barbade',
    id: 'Barbados',
    it: 'Barbados',
    kk: 'Барбадос',
    ko: '바베이도스',
    ky: 'Барбадос',
    ms: 'Barbados',
    ru: 'Барбадос',
    tr: 'Barbados',
    zh: '巴巴多斯',
  },
  lc: {
    en: 'Saint Lucia',
    ar: 'سانت لوسيا',
    az: 'Sent-Lüsiya',
    de: 'St. Lucia',
    es: 'Santa Lucía',
    fa: 'سنت لوسیا',
    fr: 'Sainte-Lucie',
    id: 'Saint Lucia',
    it: 'Saint Lucia',
    kk: 'Сент-Люсия',
    ko: '세인트루시아',
    ky: 'Сент-Люсия',
    ms: 'Saint Lucia',
    ru: 'Сент-Люсия',
    tr: 'Saint Lucia',
    zh: '圣卢西亚',
  },
  py: {
    en: 'Paraguay',
    ar: 'باراغواي',
    az: 'Paraqvay',
    de: 'Paraguay',
    es: 'Paraguay',
    fa: 'پاراگوئه',
    fr: 'Paraguay',
    id: 'Paraguay',
    it: 'Paraguay',
    kk: 'Парагвай',
    ko: '파라과이',
    ky: 'Парагвай',
    ms: 'Paraguay',
    ru: 'Парагвай',
    tr: 'Paraguay',
    zh: '巴拉圭',
  },
  gt: {
    en: 'Guatemala',
    ar: 'غواتيمالا',
    az: 'Qvatemala',
    de: 'Guatemala',
    es: 'Guatemala',
    fa: 'گواتمالا',
    fr: 'Guatemala',
    id: 'Guatemala',
    it: 'Guatemala',
    kk: 'Гватемала',
    ko: '과테말라',
    ky: 'Гватемала',
    ms: 'Guatemala',
    ru: 'Гватемала',
    tr: 'Guatemala',
    zh: '危地马拉',
  },
  tk: {
    en: 'Tokelau',
    ar: 'توكيلاو',
    az: 'Tokelau',
    de: 'Tokelau',
    es: 'Tokelau',
    fa: 'توکلائو',
    fr: 'Tokelau',
    id: 'Tokelau',
    it: 'Tokelau',
    kk: 'Токелау',
    ko: '토켈라우',
    ky: 'Токелау',
    ms: 'Tokelau',
    ru: 'Токелау',
    tr: 'Tokelau',
    zh: '托克劳',
  },
  nc: {
    en: 'New Caledonia',
    ar: 'كاليدونيا الجديدة',
    az: 'Yeni Kaledoniya',
    de: 'Neukaledonien',
    es: 'Nueva Caledonia',
    fa: 'کالدونیای جدید',
    fr: 'Nouvelle-Calédonie',
    id: 'Kaledonia Baru',
    it: 'Nuova Caledonia',
    kk: 'Жаңа Каледония',
    ko: '누벨칼레도니',
    ky: 'Жаңы Каледония',
    ms: 'New Caledonia',
    ru: 'Новая Каледония',
    tr: 'Yeni Kaledonya',
    zh: '新喀里多尼亞',
  },
  wf: {
    en: 'Wallis and Futuna',
    ar: 'واليس وفوتونا',
    az: 'Uollis və Futuna',
    de: 'Wallis und Futuna',
    es: 'Wallis y Futuna',
    fa: 'والیس و فوتونا',
    fr: 'Wallis-et-Futuna',
    id: 'Wallis dan Futuna',
    it: 'Wallis e Futuna',
    kk: 'Уоллис және Футуна',
    ko: '왈리스 푸투나',
    ky: 'Уоллис жана Футуна',
    ms: 'Wallis dan Futuna',
    ru: 'Уоллис и Футуна',
    tr: 'Wallis ve Futuna Adaları',
    zh: '瓦利斯和富圖納',
  },
  aq: {
    en: 'Antarctica',
    ar: 'القارة القطبية الجنوبية',
    az: 'Antarktida',
    de: 'Antarktika',
    es: 'Antártida',
    fa: 'جنوبگان',
    fr: 'Antarctique',
    id: 'Antarktika',
    it: 'Antartide',
    kk: 'Антарктида',
    ko: '남극',
    ky: 'Антарктида',
    ms: 'Antartika',
    ru: 'Антарктида',
    tr: 'Antarktika',
    zh: '南極洲',
  },
  sm: {
    en: 'San Marino',
    ar: 'مدينة سان مارينو',
    az: 'San-Marino',
    de: 'San Marino',
    es: 'San Marino',
    fa: 'سن مارینو',
    fr: 'Saint-Marin',
    id: 'San Marino',
    it: 'Città di San Marino',
    kk: 'Сан-Марино',
    ko: '산마리노',
    ky: 'Сан-Марино',
    ms: 'San Marino',
    ru: 'Сан-Марино',
    tr: 'San Marino',
    zh: '聖馬力諾',
  },
  hn: {
    en: 'Honduras',
    ar: 'هندوراس',
    az: 'Honduras',
    de: 'Honduras',
    es: 'Honduras',
    fa: 'هندوراس',
    fr: 'Honduras',
    id: 'Honduras',
    it: 'Honduras',
    kk: 'Гондурас',
    ko: '온두라스',
    ky: 'Гондурас',
    ms: 'Honduras',
    ru: 'Гондурас',
    tr: 'Honduras',
    zh: '洪都拉斯',
  },
  sv: {
    en: 'El Salvador',
    ar: 'السلفادور',
    az: 'Salvador',
    de: 'El Salvador',
    es: 'El Salvador',
    fa: 'السالوادور',
    fr: 'Salvador',
    id: 'El Salvador',
    it: 'El Salvador',
    kk: 'Эль-Сальвадор Республикасы',
    ko: '엘살바도르',
    ky: 'Сальвадор',
    ms: 'El Salvador',
    ru: 'Сальвадор',
    tr: 'El Salvador',
    zh: '薩爾瓦多',
  },
  ad: {
    en: 'Andorra',
    ar: 'أندورا',
    az: 'Andorra',
    de: 'Andorra',
    es: 'Andorra',
    fa: 'آندورا',
    fr: 'Andorre',
    id: 'Andorra',
    it: 'Andorra',
    kk: 'Андорра',
    ko: '안도라',
    ky: 'Андорра',
    ms: 'Andorra',
    ru: 'Андорра',
    tr: 'Andorra',
    zh: '安道尔',
  },
  mc: {
    en: 'Monaco',
    ar: 'موناكو',
    az: 'Monako',
    de: 'Monaco',
    es: 'Mónaco',
    fa: 'موناکو',
    fr: 'Monaco',
    id: 'Monako',
    it: 'Monaco',
    kk: 'Монако',
    ko: '모나코',
    ky: 'Монако',
    ms: 'Monaco',
    ru: 'Монако',
    tr: 'Monako',
    zh: '摩納哥',
  },
  tj: {
    en: 'Tajikistan',
    ar: 'طاجيكستان',
    az: 'Tacikistan',
    de: 'Tadschikistan',
    es: 'Tayikistán',
    fa: 'تاجیکستان',
    fr: 'Tadjikistan',
    id: 'Tajikistan',
    it: 'Tagikistan',
    kk: 'Тәжікстан',
    ko: '타지키스탄',
    ky: 'Тажикстан',
    ms: 'Tajikistan',
    ru: 'Таджикистан',
    tr: 'Tacikistan',
    zh: '塔吉克斯坦',
  },
  fo: {
    en: 'Faroe Islands',
    ar: 'جزر فارو',
    az: 'Farer adaları',
    de: 'Färöer',
    es: 'Islas Feroe',
    fa: 'جزایر فارو',
    fr: 'îles Féroé',
    id: 'Kepulauan Faroe',
    it: 'Fær Øer',
    kk: 'Фарер аралдары',
    ko: '페로 제도',
    ky: 'Фарер аралдары',
    ms: 'Kepulauan Faroe',
    ru: 'Фарерские острова',
    tr: 'Faroe Adaları',
    zh: '法罗群岛',
  },
  bw: {
    en: 'Botswana',
    ar: 'بوتسوانا',
    az: 'Botsvana',
    de: 'Botswana',
    es: 'Botsuana',
    fa: 'بوتسوانا',
    fr: 'Botswana',
    id: 'Botswana',
    it: 'Botswana',
    kk: 'Ботсвана',
    ko: '보츠와나',
    ky: 'Ботсвана',
    ms: 'Botswana',
    ru: 'Ботсвана',
    tr: 'Botsvana',
    zh: '波札那',
  },
  ml: {
    en: 'Mali',
    ar: 'مالي',
    az: 'Mali',
    de: 'Mali',
    es: 'Mali',
    fa: 'مالی',
    fr: 'Mali',
    id: 'Mali',
    it: 'Mali',
    kk: 'Мали',
    ko: '말리',
    ky: 'Мали',
    ms: 'Mali',
    ru: 'Мали',
    tr: 'Mali',
    zh: '马里',
  },
  mz: {
    en: 'Mozambique',
    ar: 'موزمبيق',
    az: 'Mozambik',
    de: 'Mosambik',
    es: 'Mozambique',
    fa: 'موزامبیک',
    fr: 'Mozambique',
    id: 'Mozambique',
    it: 'Mozambico',
    kk: 'Мозамбик',
    ko: '모잠비크',
    ky: 'Мозамбик',
    ms: 'Mozambique',
    ru: 'Мозамбик',
    tr: 'Mozambik',
    zh: '莫桑比克',
  },
  lr: {
    en: 'Liberia',
    ar: 'ليبيريا',
    az: 'Liberiya',
    de: 'Liberia',
    es: 'Liberia',
    fa: 'لیبریا',
    fr: 'Liberia',
    id: 'Liberia',
    it: 'Liberia',
    kk: 'Либерия',
    ko: '라이베리아',
    ky: 'Либерия',
    ms: 'Liberia',
    ru: 'Либерия',
    tr: 'Liberya',
    zh: '利比里亞',
  },
  tn: {
    en: 'Tunisia',
    ar: 'تونس',
    az: 'Tunis',
    de: 'Tunesien',
    es: 'Túnez',
    fa: 'تونس',
    fr: 'Tunisie',
    id: 'Tunisia',
    it: 'Tunisia',
    kk: 'Тунис',
    ko: '튀니지',
    ky: 'Тунис',
    ms: 'Tunisia',
    ru: 'Тунис',
    tr: 'Tunus',
    zh: '突尼西亞',
  },
  mg: {
    en: 'Madagascar',
    ar: 'مدغشقر',
    az: 'Madaqaskar',
    de: 'Madagaskar',
    es: 'Madagascar',
    fa: 'ماداگاسکار',
    fr: 'Madagascar',
    id: 'Madagaskar',
    it: 'Madagascar',
    kk: 'Мадагаскар',
    ko: '마다가스카르',
    ky: 'Мадагаскар Республикасы',
    ms: 'Madagaskar',
    ru: 'Мадагаскар',
    tr: 'Madagaskar',
    zh: '馬達加斯加',
  },
  ao: {
    en: 'Angola',
    ar: 'أنغولا',
    az: 'Anqola',
    de: 'Angola',
    es: 'Angola',
    fa: 'آنگولا',
    fr: 'Angola',
    id: 'Angola',
    it: 'Angola',
    kk: 'Ангола',
    ko: '앙골라',
    ky: 'Ангола',
    ms: 'Angola',
    ru: 'Ангола',
    tr: 'Angola',
    zh: '安哥拉',
  },
  na: {
    en: 'Namibia',
    ar: 'ناميبيا',
    az: 'Namibiya',
    de: 'Namibia',
    es: 'Namibia',
    fa: 'نامیبیا',
    fr: 'Namibie',
    id: 'Namibia',
    it: 'Namibia',
    kk: 'Намибия',
    ko: '나미비아',
    ky: 'Намибия',
    ms: 'Namibia',
    ru: 'Намибия',
    tr: 'Namibya',
    zh: '纳米比亚',
  },
  ci: {
    en: "Cote D'ivoire",
    ar: 'ساحل العاج',
    az: "Kot-d'İvuar",
    de: 'Elfenbeinküste',
    es: 'Costa de Marfil',
    fa: 'ساحل عاج',
    fr: "Côte d'Ivoire",
    id: 'Pantai Gading',
    it: "Costa d'Avorio",
    kk: 'Кот-д-Ивуар',
    ko: '코트디부아르',
    ky: 'Кот-д-Ивуар',
    ms: 'Ivory Coast',
    ru: 'Кот-д’Ивуар',
    tr: 'Fildişi Sahili',
    zh: '科特迪瓦',
  },
  sd: {
    en: 'Sudan',
    ar: 'السودان',
    az: 'Sudan',
    de: 'Sudan',
    es: 'Sudán',
    fa: 'سودان',
    fr: 'Soudan',
    id: 'Sudan',
    it: 'Sudan',
    kk: 'Сұдан',
    ko: '수단',
    ky: 'Судан',
    ms: 'Sudan',
    ru: 'Судан',
    tr: 'Sudan',
    zh: '苏丹',
  },
  mw: {
    en: 'Malawi',
    ar: 'مالاوي',
    az: 'Malavi',
    de: 'Malawi',
    es: 'Malaui',
    fa: 'مالاوی',
    fr: 'Malawi',
    id: 'Malawi',
    it: 'Malawi',
    kk: 'Малави Республикасы',
    ko: '말라위',
    ky: 'Малави',
    ms: 'Malawi',
    ru: 'Малави',
    tr: 'Malavi',
    zh: '馬拉威',
  },
  bj: {
    en: 'Benin',
    ar: 'بنين',
    az: 'Benin',
    de: 'Benin',
    es: 'Benín',
    fa: 'بنین',
    fr: 'Bénin',
    id: 'Benin',
    it: 'Benin',
    kk: 'Бенин',
    ko: '베냉',
    ky: 'Бенин',
    ms: 'Benin',
    ru: 'Бенин',
    tr: 'Benin',
    zh: '貝南',
  },
  rw: {
    en: 'Rwanda',
    ar: 'رواندا',
    az: 'Ruanda',
    de: 'Ruanda',
    es: 'Ruanda',
    fa: 'رواندا',
    fr: 'Rwanda',
    id: 'Rwanda',
    it: 'Ruanda',
    kk: 'Руанда',
    ko: '르완다',
    ky: 'Руанда',
    ms: 'Rwanda',
    ru: 'Руанда',
    tr: 'Ruanda',
    zh: '卢旺达',
  },
  cg: {
    en: 'Congo',
    ar: 'نهر الكونغو',
    az: 'Konqo',
    de: 'Kongo',
    es: 'Congo',
    fa: 'کنگو',
    fr: 'Congo',
    id: 'Sungai Kongo',
    it: 'Congo',
    kk: 'Конго',
    ko: '콩고강',
    ky: 'Конго',
    ms: 'Sungai Congo',
    ru: 'Конго',
    tr: 'Kongo Nehri',
    zh: '刚果河',
  },
  ls: {
    en: 'Lesotho',
    ar: 'ليسوتو',
    az: 'Lesoto',
    de: 'Lesotho',
    es: 'Lesoto',
    fa: 'لسوتو',
    fr: 'Lesotho',
    id: 'Lesotho',
    it: 'Lesotho',
    kk: 'Лесото',
    ko: '레소토',
    ky: 'Лесото',
    ms: 'Lesotho',
    ru: 'Лесото',
    tr: 'Lesotho',
    zh: '莱索托',
  },
  gn: {
    en: 'Guinea',
    ar: 'غينيا',
    az: 'Qvineya',
    de: 'Guinea',
    es: 'Guinea',
    fa: 'گینه',
    fr: 'Guinée',
    id: 'Guinea',
    it: 'Guinea',
    kk: 'Гвинея',
    ko: '기니',
    ky: 'Гвинея',
    ms: 'Guinea',
    ru: 'Гвинея',
    tr: 'Gine',
    zh: '几内亚',
  },
  bf: {
    en: 'Burkina Faso',
    ar: 'بوركينا فاسو',
    az: 'Burkina-Faso',
    de: 'Burkina Faso',
    es: 'Burkina Faso',
    fa: 'بورکینافاسو',
    fr: 'Burkina Faso',
    id: 'Burkina Faso',
    it: 'Burkina Faso',
    kk: 'Буркина-Фасо',
    ko: '부르키나파소',
    ky: 'Буркина Фасо',
    ms: 'Burkina Faso',
    ru: 'Буркина-Фасо',
    tr: 'Burkina Faso',
    zh: '布吉納法索',
  },
  so: {
    en: 'Somalia',
    ar: 'الصومال',
    az: 'Somali',
    de: 'Somalia',
    es: 'Somalia',
    fa: 'سومالی',
    fr: 'Somalie',
    id: 'Somalia',
    it: 'Somalia',
    kk: 'Сомали',
    ko: '소말리아',
    ky: 'Сомали',
    ms: 'Somalia',
    ru: 'Сомали',
    tr: 'Somali',
    zh: '索馬里',
  },
  sl: {
    en: 'Sierra Leone',
    ar: 'سيراليون',
    az: 'Syerra-Leone',
    de: 'Sierra Leone',
    es: 'Sierra Leona',
    fa: 'سیرالئون',
    fr: 'Sierra Leone',
    id: 'Sierra Leone',
    it: 'Sierra Leone',
    kk: 'Сиерра-Леоне',
    ko: '시에라리온',
    ky: 'Сьерра-Леоне',
    ms: 'Sierra Leone',
    ru: 'Сьерра-Леоне',
    tr: 'Sierra Leone',
    zh: '塞拉利昂',
  },
  ne: {
    en: 'Niger',
    ar: 'النيجر',
    az: 'Niger',
    de: 'Niger',
    es: 'Níger',
    fa: 'نیجر',
    fr: 'Niger',
    id: 'Niger',
    it: 'Niger',
    kk: 'Нигер',
    ko: '니제르',
    ky: 'Нигер',
    ms: 'Niger',
    ru: 'Нигер',
    tr: 'Nijer',
    zh: '尼日尔',
  },
  cf: {
    en: 'Central African Republic',
    ar: 'جمهورية إفريقيا الوسطى',
    az: 'Mərkəzi Afrika Respublikası',
    de: 'Zentralafrikanische Republik',
    es: 'República Centroafricana',
    fa: 'جمهوری آفریقای مرکزی',
    fr: 'République centrafricaine',
    id: 'Republik Afrika Tengah',
    it: 'Repubblica Centrafricana',
    kk: 'Орталық Африка Республикасы',
    ko: '중앙아프리카 공화국',
    ky: 'Борбордук-Африка Республикасы',
    ms: 'Republik Afrika Tengah',
    ru: 'Центральноафриканская Республика',
    tr: 'Orta Afrika Cumhuriyeti',
    zh: '中非共和國',
  },
  tg: {
    en: 'Togo',
    ar: 'توغو',
    az: 'Toqo',
    de: 'Togo',
    es: 'Togo',
    fa: 'توگو',
    fr: 'Togo',
    id: 'Togo',
    it: 'Togo',
    kk: 'Того',
    ko: '토고',
    ky: 'Того',
    ms: 'Togo',
    ru: 'Того',
    tr: 'Togo',
    zh: '多哥',
  },
  ga: {
    en: 'Gabon',
    ar: 'الغابون',
    az: 'Qabon',
    de: 'Gabun',
    es: 'Gabón',
    fa: 'گابن',
    fr: 'Gabon',
    id: 'Gabon',
    it: 'Gabon',
    kk: 'Габон',
    ko: '가봉',
    ky: 'Габон',
    ms: 'Gabon',
    ru: 'Габон',
    tr: 'Gabon',
    zh: '加蓬',
  },
  gq: {
    en: 'Equatorial Guinea',
    ar: 'غينيا الاستوائية',
    az: 'Ekvatorial Qvineya',
    de: 'Äquatorialguinea',
    es: 'Guinea Ecuatorial',
    fa: 'گینه استوایی',
    fr: 'Guinée équatoriale',
    id: 'Guinea Khatulistiwa',
    it: 'Guinea Equatoriale',
    kk: 'Экваторлық Гвинея',
    ko: '적도 기니',
    ky: 'Экваториалдык Гвинея',
    ms: 'Guinea Khatulistiwa',
    ru: 'Экваториальная Гвинея',
    tr: 'Ekvator Ginesi',
    zh: '赤道几内亚',
  },
  sn: {
    en: 'Senegal',
    ar: 'السنغال',
    az: 'Seneqal',
    de: 'Senegal',
    es: 'Senegal',
    fa: 'سنگال',
    fr: 'Sénégal',
    id: 'Senegal',
    it: 'Senegal',
    kk: 'Сенегал',
    ko: '세네갈',
    ky: 'Сенегал',
    ms: 'Senegal',
    ru: 'Сенегал',
    tr: 'Senegal',
    zh: '塞内加尔',
  },
  dz: {
    en: 'Algeria',
    ar: 'الجزائر',
    az: 'Əlcəzair',
    de: 'Algerien',
    es: 'Argelia',
    fa: 'الجزایر',
    fr: 'Algérie',
    id: 'Aljazair',
    it: 'Algeria',
    kk: 'Алжир',
    ko: '알제리',
    ky: 'Алжир',
    ms: 'Algeria',
    ru: 'Алжир',
    tr: 'Cezayir',
    zh: '阿爾及利亞',
  },
  as: {
    en: 'American Samoa',
    ar: 'ساموا الأمريكية',
    az: 'Amerika Samoası',
    de: 'Amerikanisch-Samoa',
    es: 'Samoa Estadounidense',
    fa: 'ساموآی آمریکا',
    fr: 'Samoa américaines',
    id: 'Samoa Amerika',
    it: 'Samoa Americane',
    kk: 'Американ Самоасы',
    ko: '아메리칸사모아',
    ky: 'Америка Самоасы',
    ms: 'Samoa Amerika',
    ru: 'Американское Самоа',
    tr: 'Amerikan Samoası',
    zh: '美屬薩摩亞',
  },
  mr: {
    en: 'Mauritania',
    ar: 'موريتانيا',
    az: 'Mavritaniya',
    de: 'Mauretanien',
    es: 'Mauritania',
    fa: 'موریتانی',
    fr: 'Mauritanie',
    id: 'Mauritania',
    it: 'Mauritania',
    kk: 'Мавритания',
    ko: '모리타니',
    ky: 'Мавритания',
    ms: 'Mauritania',
    ru: 'Мавритания',
    tr: 'Moritanya',
    zh: '毛里塔尼亞',
  },
  dj: {
    en: 'Djibouti',
    ar: 'جيبوتي',
    az: 'Cibuti',
    de: 'Dschibuti',
    es: 'Yibuti',
    fa: 'جیبوتی',
    fr: 'Djibouti',
    id: 'Djibouti',
    it: 'Gibuti',
    kk: 'Джибути',
    ko: '지부티',
    ky: 'Жибути',
    ms: 'Djibouti',
    ru: 'Джибути',
    tr: 'Cibuti',
    zh: '吉布提',
  },
  km: {
    en: 'Comoros',
    ar: 'جزر القمر',
    az: 'Komor adaları',
    de: 'Komoren',
    es: 'Comoras',
    fa: 'مجمعالجزایر قمر',
    fr: 'Comores',
    id: 'Komoro',
    it: 'Comore',
    kk: 'Камарлар',
    ko: '코모로',
    ky: 'Комор',
    ms: 'Comoros',
    ru: 'Коморы',
    tr: 'Komorlar',
    zh: '葛摩',
  },
  io: {
    en: 'British Indian Ocean Territory',
    ar: 'إقليم المحيط الهندي البريطاني',
    az: 'Britaniya Hind okeanı əraziləri',
    de: 'Britisches Territorium im Indischen Ozean',
    es: 'Territorio Británico del Océano Índico',
    fa: 'قلمرو بریتانیا در اقیانوس هند',
    fr: 'Territoire britannique de l’océan Indien',
    id: 'Wilayah Samudra Hindia Inggris',
    it: "Territorio Britannico dell'Oceano Indiano",
    kk: 'Үнді мұхитындағы Британия аймағы',
    ko: '영국령 인도양 지역',
    ky: 'Инди океанындагы Британ территориясы',
    ms: 'Wilayah Lautan Hindi British',
    ru: 'Британская территория в Индийском океане',
    tr: 'Britanya Hint Okyanusu Toprakları',
    zh: '英屬印度洋領地',
  },
  td: {
    en: 'Chad',
    ar: 'تشاد',
    az: 'Çad',
    de: 'Tschad',
    es: 'Chad',
    fa: 'چاد',
    fr: 'Tchad',
    id: 'Chad',
    it: 'Ciad',
    kk: 'Ташад',
    ko: '차드',
    ky: 'Чад',
    ms: 'Chad',
    ru: 'Чад',
    tr: 'Çad',
    zh: '乍得',
  },
  nr: {
    en: 'Nauru',
    ar: 'ناورو',
    az: 'Nauru',
    de: 'Nauru',
    es: 'Nauru',
    fa: 'نائورو',
    fr: 'Nauru',
    id: 'Nauru',
    it: 'Nauru',
    kk: 'Науру',
    ko: '나우루',
    ky: 'Науру',
    ms: 'Nauru',
    ru: 'Науру',
    tr: 'Nauru',
    zh: '瑙鲁',
  },
  ws: {
    en: 'Samoa',
    ar: 'ساموا',
    az: 'Samoa',
    de: 'Samoa',
    es: 'Samoa',
    fa: 'ساموآ',
    fr: 'Samoa',
    id: 'Samoa',
    it: 'Samoa',
    kk: 'Самоа',
    ko: '사모아',
    ky: 'Самоа',
    ms: 'Samoa',
    ru: 'Самоа',
    tr: 'Samoa',
    zh: '萨摩亚',
  },
  pf: {
    en: 'French Polynesia',
    ar: 'بولينزيا الفرنسية',
    az: 'Fransa Polineziyası',
    de: 'Französisch-Polynesien',
    es: 'Polinesia Francesa',
    fa: 'پلینزی فرانسه',
    fr: 'Polynésie française',
    id: 'Polinesia Prancis',
    it: 'Polinesia francese',
    kk: 'Франция Полинезиясы',
    ko: '프랑스령 폴리네시아',
    ky: 'Полинезия',
    ms: 'Polinesia Perancis',
    ru: 'Французская Полинезия',
    tr: 'Fransız Polinezyası',
    zh: '法屬玻里尼西亞',
  },
  ht: {
    en: 'Haiti',
    ar: 'هايتي',
    az: 'Haiti',
    de: 'Haiti',
    es: 'Haití',
    fa: 'هائیتی',
    fr: 'Haïti',
    id: 'Haiti',
    it: 'Haiti',
    kk: 'Гаити',
    ko: '아이티',
    ky: 'Гаити Республикасы',
    ms: 'Haiti',
    ru: 'Гаити',
    tr: 'Haiti',
    zh: '海地',
  },
  sr: {
    en: 'Suriname',
    ar: 'سورينام',
    az: 'Surinam',
    de: 'Suriname',
    es: 'Surinam',
    fa: 'سورینام',
    fr: 'Suriname',
    id: 'Suriname',
    it: 'Suriname',
    kk: 'Суринам',
    ko: '수리남',
    ky: 'Суринам',
    ms: 'Suriname',
    ru: 'Суринам',
    tr: 'Surinam',
    zh: '蘇利南',
  },
  et: {
    en: 'Ethiopia',
    ar: 'إثيوبيا',
    az: 'Efiopiya',
    de: 'Äthiopien',
    es: 'Etiopía',
    fa: 'اتیوپی',
    fr: 'Éthiopie',
    id: 'Ethiopia',
    it: 'Etiopia',
    kk: 'Ефиопия',
    ko: '에티오피아',
    ky: 'Эфиопия',
    ms: 'Habsyah',
    ru: 'Эфиопия',
    tr: 'Etiyopya',
    zh: '埃塞俄比亚',
  },
  bm: {
    en: 'Bermuda',
    ar: 'برمودا',
    az: 'Bermud adaları',
    de: 'Bermuda',
    es: 'Bermudas',
    fa: 'برمودا',
    fr: 'Bermudes',
    id: 'Bermuda',
    it: 'Bermuda',
    kk: 'Бермудалар',
    ko: '버뮤다',
    ky: 'Бермуд аралдары',
    ms: 'Bermuda',
    ru: 'Бермудские острова',
    tr: 'Bermuda',
    zh: '百慕大',
  },
  ms: {
    en: 'Montserrat',
    ar: 'مونتسرات',
    az: 'Montserrat',
    de: 'Montserrat',
    es: 'Montserrat',
    fa: 'مونتسرات',
    fr: 'Montserrat',
    id: 'Montserrat',
    it: 'Montserrat',
    kk: 'Монтсеррат',
    ko: '몬트세랫',
    ky: 'Монтсеррат',
    ms: 'Montserrat',
    ru: 'Монтсеррат',
    tr: 'Montserrat',
    zh: '蒙塞拉特島',
  },
  bz: {
    en: 'Belize',
    ar: 'بليز',
    az: 'Beliz',
    de: 'Belize',
    es: 'Belice',
    fa: 'بلیز',
    fr: 'Belize',
    id: 'Belize',
    it: 'Belize',
    kk: 'Белиз',
    ko: '벨리즈',
    ky: 'Белиз',
    ms: 'Belize',
    ru: 'Белиз',
    tr: 'Belize',
    zh: '伯利兹',
  },
  nu: {
    en: 'Niue',
    ar: 'نييوي',
    az: 'Niue',
    de: 'Niue',
    es: 'Niue',
    fa: 'نیووی',
    fr: 'Niue',
    id: 'Niue',
    it: 'Niue',
    kk: 'Ниуе',
    ko: '니우에',
    ky: 'Ниуэ аралы',
    ms: 'Niue',
    ru: 'Ниуэ',
    tr: 'Niue',
    zh: '紐埃',
  },
  tv: {
    en: 'Tuvalu',
    ar: 'توفالو',
    az: 'Tuvalu',
    de: 'Tuvalu',
    es: 'Tuvalu',
    fa: 'تووالو',
    fr: 'Tuvalu',
    id: 'Tuvalu',
    it: 'Tuvalu',
    kk: 'Туалу',
    ko: '투발루',
    ky: 'Тувалу',
    ms: 'Tuvalu',
    ru: 'Тувалу',
    tr: 'Tuvalu',
    zh: '吐瓦魯',
  },
  pw: {
    en: 'Palau',
    ar: 'بالاو',
    az: 'Palau',
    de: 'Palau',
    es: 'Palaos',
    fa: 'پالائو',
    fr: 'Palaos',
    id: 'Palau',
    it: 'Palau',
    kk: 'Палау Республикасы',
    ko: '팔라우',
    ky: 'Палау',
    ms: 'Palau',
    ru: 'Палау',
    tr: 'Palau',
    zh: '帛琉',
  },
  ki: {
    en: 'Kiribati',
    ar: 'كيريباتي',
    az: 'Kiribati',
    de: 'Kiribati',
    es: 'Kiribati',
    fa: 'کیریباتی',
    fr: 'Kiribati',
    id: 'Kiribati',
    it: 'Kiribati',
    kk: 'Кирибати',
    ko: '키리바시',
    ky: 'Кирибати',
    ms: 'Kiribati',
    ru: 'Кирибати',
    tr: 'Kiribati',
    zh: '吉里巴斯',
  },
  aw: {
    en: 'Aruba',
    ar: 'أروبا',
    az: 'Aruba',
    de: 'Aruba',
    es: 'Aruba',
    fa: 'آروبا',
    fr: 'Aruba',
    id: 'Aruba',
    it: 'Aruba',
    kk: 'Аруба',
    ko: '아루바',
    ky: 'Аруба',
    ms: 'Aruba',
    ru: 'Аруба',
    tr: 'Aruba',
    zh: '阿魯巴',
  },
  gy: {
    en: 'Guyana',
    ar: 'غيانا',
    az: 'Qayana',
    de: 'Guyana',
    es: 'Guyana',
    fa: 'گویان',
    fr: 'Guyana',
    id: 'Guyana',
    it: 'Guyana',
    kk: 'Гайана',
    ko: '가이아나',
    ky: 'Гайана',
    ms: 'Guyana',
    ru: 'Гайана',
    tr: 'Guyana',
    zh: '圭亚那',
  },
  st: {
    en: 'Sao Tome and Principe',
    ar: 'ساو تومي وبرينسيب',
    az: 'San Tome və Prinsipi',
    de: 'São Tomé und Príncipe',
    es: 'Santo Tomé y Príncipe',
    fa: 'سائوتومه و پرینسیپ',
    fr: 'Sao Tomé-et-Principe',
    id: 'Sao Tome dan Principe',
    it: 'São Tomé e Príncipe',
    kk: 'Сан-Томе және Принсипи',
    ko: '상투메 프린시페',
    ky: 'Сан-Томе жана Принсипи',
    ms: 'São Tomé dan Príncipe',
    ru: 'Сан-Томе и Принсипи',
    tr: 'São Tomé ve Príncipe',
    zh: '圣多美和普林西比',
  },
  er: {
    en: 'Eritrea',
    ar: 'إرتريا',
    az: 'Eritreya',
    de: 'Eritrea',
    es: 'Eritrea',
    fa: 'اریتره',
    fr: 'Érythrée',
    id: 'Eritrea',
    it: 'Eritrea',
    kk: 'Эритрея',
    ko: '에리트레아',
    ky: 'Эритрея',
    ms: 'Eritrea',
    ru: 'Эритрея',
    tr: 'Eritre',
    zh: '厄立特里亞',
  },
  gw: {
    en: 'Guinea-Bissau',
    ar: 'غينيا بيساو',
    az: 'Qvineya-Bisau',
    de: 'Guinea-Bissau',
    es: 'Guinea-Bisáu',
    fa: 'گینه بیسائو',
    fr: 'Guinée-Bissau',
    id: 'Guinea-Bissau',
    it: 'Guinea-Bissau',
    kk: 'Гвинея-Бисау',
    ko: '기니비사우',
    ky: 'Гвинея-Бисау',
    ms: 'Guinea-Bissau',
    ru: 'Гвинея-Бисау',
    tr: 'Gine-Bissau',
    zh: '畿內亞比紹',
  },
  tm: {
    en: 'Turkmenistan',
    ar: 'تركمانستان',
    az: 'Türkmənistan',
    de: 'Turkmenistan',
    es: 'Turkmenistán',
    fa: 'ترکمنستان',
    fr: 'Turkménistan',
    id: 'Turkmenistan',
    it: 'Turkmenistan',
    kk: 'Түрікменстан',
    ko: '투르크메니스탄',
    ky: 'Түркмөнстан',
    ms: 'Turkmenistan',
    ru: 'Туркменистан',
    tr: 'Türkmenistan',
    zh: '土庫曼斯坦',
  },
  fk: {
    en: 'Falkland Islands [Malvinas]',
    ar: 'جزر فوكلاند',
    az: 'Folklend adaları',
    de: 'Falklandinseln',
    es: 'Islas Malvinas',
    fa: 'جزایر فالکلند',
    fr: 'îles Malouines',
    id: 'Kepulauan Falkland',
    it: 'isole Falkland',
    kk: 'Фолкленд аралдары',
    ko: '포클랜드 제도',
    ky: 'Фолкленд',
    ms: 'Kepulauan Falkland',
    ru: 'Фолклендские острова',
    tr: 'Falkland Adaları',
    zh: '福克蘭群島',
  },
  ai: {
    en: 'Anguilla',
    ar: 'أنغويلا',
    az: 'Angilya',
    de: 'Anguilla',
    es: 'Anguila',
    fa: 'آنگویلا',
    fr: 'Anguilla',
    id: 'Anguilla',
    it: 'Anguilla',
    kk: 'Ангилья',
    ko: '앵귈라',
    ky: 'Ангилья',
    ms: 'Anguilla',
    ru: 'Ангилья',
    tr: 'Anguilla',
    zh: '安圭拉',
  },
  tc: {
    en: 'Turks and Caicos Islands',
    ar: 'جزر توركس وكايكوس',
    az: 'Törks və Kaykos',
    de: 'Turks- und Caicosinseln',
    es: 'Islas Turcas y Caicos',
    fa: 'جزایر تورکس و کایکوس',
    fr: 'Îles Turques et Caïques',
    id: 'Kepulauan Turks dan Caicos',
    it: 'Turks e Caicos',
    kk: 'Төркс пен Кайкос',
    ko: '터크스 케이커스 제도',
    ky: 'Теркс жана Кайкос аралдары',
    ms: 'Kepulauan Turks dan Caicos',
    ru: 'Теркс и Кайкос',
    tr: 'Turks ve Caicos Adaları',
    zh: '特克斯和凯科斯群岛',
  },
  kr: {
    en: 'South Korea',
    ar: 'كوريا الجنوبية',
    az: 'Cənubi Koreya',
    de: 'Südkorea',
    es: 'Corea del Sur',
    fa: 'کره جنوبی',
    fr: 'Corée du Sud',
    id: 'Korea Selatan',
    it: 'Corea del Sud',
    kk: 'Оңтүстік Корея',
    ko: '대한민국',
    ky: 'Түштүк Корея',
    ms: 'Korea Selatan',
    ru: 'Южная Корея',
    tr: 'Güney Kore',
    zh: '韩国',
  },
  tw: {
    en: 'Taiwan',
    ar: 'تايوان',
    az: 'Tayvan',
    de: 'Taiwan',
    es: 'Taiwán',
    fa: 'تایوان',
    fr: 'Taïwan',
    id: 'Taiwan',
    it: 'Taiwan',
    kk: 'Тайвань',
    ko: '대만',
    ky: 'Тайвань',
    ms: 'Taiwan',
    ru: 'Тайвань',
    tr: 'Tayvan',
    zh: '台湾',
  },
  gb: {
    en: 'United Kingdom',
    ar: 'المملكة المتحدة',
    az: 'Birləşmiş Krallıq',
    de: 'Vereinigtes Königreich',
    es: 'Reino Unido',
    fa: 'بریتانیا',
    fr: 'Royaume-Uni',
    id: 'Britania Raya',
    it: 'Regno Unito',
    kk: 'Ұлыбритания',
    ko: '영국',
    ky: 'Улуу Британия',
    ms: 'United Kingdom',
    ru: 'Соединённое Королевство',
    tr: 'Birleşik Krallık',
    zh: '英国',
  },
  cz: {
    en: 'Czech Republic',
    ar: 'جمهورية التشيك',
    az: 'Çex Respublikası',
    de: 'Tschechische Republik',
    es: 'República Checa',
    fa: 'جمهوری چک',
    fr: 'République tchèque',
    id: 'Republik Ceko',
    it: 'Repubblica Ceca',
    kk: 'Чехия',
    ko: '체코',
    ky: 'Чех Республикасы',
    ms: 'Republik Czech',
    ru: 'Чехия',
    tr: 'Çek Cumhuriyeti',
    zh: '捷克共和国',
  },
  nl: {
    en: 'Netherlands',
    ar: 'هولندا',
    az: 'Niderlandlar',
    de: 'Niederlande',
    es: 'Países Bajos',
    fa: 'هلند',
    fr: 'Pays-Bas',
    id: 'Belanda',
    it: 'Paesi Bassi',
    kk: 'Нидерланд',
    ko: '네덜란드',
    ky: 'Нидерланддар',
    ms: 'Belanda',
    ru: 'Нидерланды',
    tr: 'Hollanda',
    zh: '荷兰',
  },
  ru: {
    en: 'Russia',
    ar: 'روسيا',
    az: 'Rusiya',
    de: 'Russland',
    es: 'Rusia',
    fa: 'روسیه',
    fr: 'Russie',
    id: 'Rusia',
    it: 'Russia',
    kk: 'Ресей',
    ko: '러시아',
    ky: 'Россия',
    ms: 'Rusia',
    ru: 'Россия',
    tr: 'Rusya',
    zh: '俄罗斯',
  },
  tz: {
    en: 'Tanzania',
    ar: 'تنزانيا',
    az: 'Tanzaniya',
    de: 'Tansania',
    es: 'Tanzania',
    fa: 'تانزانیا',
    fr: 'Tanzanie',
    id: 'Tanzania',
    it: 'Tanzania',
    kk: 'Танзания',
    ko: '탄자니아',
    ky: 'Танзания',
    ms: 'Tanzania',
    ru: 'Танзания',
    tr: 'Tanzanya',
    zh: '坦桑尼亚',
  },
  md: {
    en: 'Moldova',
    ar: 'مولدوفا',
    az: 'Moldova',
    de: 'Moldawien',
    es: 'Moldavia',
    fa: 'مولداوی',
    fr: 'Moldavie',
    id: 'Moldova',
    it: 'Moldavia',
    kk: 'Молдова',
    ko: '몰도바',
    ky: 'Молдова',
    ms: 'Moldova',
    ru: 'Молдова',
    tr: 'Moldova',
    zh: '摩尔多瓦',
  },
  va: {
    en: 'Vatican City',
    ar: 'مدينة الفاتيكان',
    az: 'Vatikan',
    de: 'Vatikanstadt',
    es: 'Ciudad del Vaticano',
    fa: 'واتیکان',
    fr: 'Cité du Vatican',
    id: 'Kota Vatikan',
    it: 'Città del Vaticano',
    kk: 'Ватикан',
    ko: '바티칸 시국',
    ky: 'Ватикан',
    ms: 'Vatican City',
    ru: 'Ватикан',
    tr: 'Vatikan Şehri',
    zh: '梵蒂冈',
  },
  ir: {
    en: 'Iran',
    ar: 'إيران',
    az: 'İran',
    de: 'Iran',
    es: 'Irán',
    fa: 'ایران',
    fr: 'Iran',
    id: 'Iran',
    it: 'Iran',
    kk: 'Иран',
    ko: '이란',
    ky: 'Иран',
    ms: 'Iran',
    ru: 'Иран',
    tr: 'İran',
    zh: '伊朗',
  },
  gg: {
    en: 'Guernsey',
    ar: 'غيرنزي',
    az: 'Gernsi',
    de: 'Guernsey',
    es: 'Guernsey',
    fa: 'گرنزی',
    fr: 'Guernesey',
    id: 'Guernsey',
    it: 'Guernsey',
    kk: 'Гернси',
    ko: '건지',
    ky: 'Гернси',
    ms: 'Guernsey',
    ru: 'Гернси',
    tr: 'Guernsey',
    zh: '根西岛',
  },
  mf: {
    en: 'Saint Martin',
    ar: 'سانت مارتن',
    az: 'Sent-Martin',
    de: 'Saint-Martin',
    es: 'San Martín',
    fa: 'سنت مارتن',
    fr: 'Saint-Martin',
    id: 'Saint Martin',
    it: 'Saint Martin',
    kk: 'Сен-Мартен',
    ko: '생마르탱',
    ky: 'Сент-Мартин',
    ms: 'Saint Martin',
    ru: 'Сен-Мартен',
    tr: 'Saint Martin',
    zh: '圣马丁',
  },
  cd: {
    en: 'Democratic Republic of the Congo',
    ar: 'جمهورية الكونغو الديمقراطية',
    az: 'Konqo Demokratik Respublikası',
    de: 'Demokratische Republik Kongo',
    es: 'República Democrática del Congo',
    fa: 'جمهوری دموکراتیک کنگو',
    fr: 'République démocratique du Congo',
    id: 'Republik Demokratik Kongo',
    it: 'Repubblica Democratica del Congo',
    kk: 'Конго Демократиялық Республикасы',
    ko: '콩고 민주 공화국',
    ky: 'Конго Демократиялык Республикасы',
    ms: 'Republik Demokratik Congo',
    ru: 'Демократическая Республика Конго',
    tr: 'Kongo Demokratik Cumhuriyeti',
    zh: '刚果民主共和国',
  },
  ve: {
    en: 'Venezuela',
    ar: 'فنزويلا',
    az: 'Venesuela',
    de: 'Venezuela',
    es: 'Venezuela',
    fa: 'ونزوئلا',
    fr: 'Venezuela',
    id: 'Venezuela',
    it: 'Venezuela',
    kk: 'Венесуэла',
    ko: '베네수엘라',
    ky: 'Венесуэла',
    ms: 'Venezuela',
    ru: 'Венесуэла',
    tr: 'Venezuela',
    zh: '委内瑞拉',
  },
  vi: {
    en: 'U.S. Virgin Islands',
    ar: 'جزر العذراء الأمريكية',
    az: 'ABŞ Virgin Adaları',
    de: 'Amerikanische Jungferninseln',
    es: 'Islas Vírgenes de los Estados Unidos',
    fa: 'جزایر ویرجین آمریکا',
    fr: 'Îles Vierges des États-Unis',
    id: 'Kepulauan Virgin AS',
    it: 'Isole Vergini americane',
    kk: 'АҚШ Виргин аралдары',
    ko: '미국령 버진아일랜드',
    ky: 'АКШнын Виргин аралдары',
    ms: 'Kepulauan Virgin AS',
    ru: 'Американские Виргинские острова',
    tr: 'ABD Virgin Adaları',
    zh: '美属维尔京群岛',
  },
  cc: {
    en: 'Cocos (Keeling) Islands',
    ar: 'جزر كوكوس',
    az: 'Kokos (Kiling) Adaları',
    de: 'Kokosinseln',
    es: 'Islas Cocos',
    fa: 'جزایر کوکوس',
    fr: 'Îles Cocos',
    id: 'Kepulauan Cocos',
    it: 'Isole Cocos',
    kk: 'Кокос аралдары',
    ko: '코코스 제도',
    ky: 'Кокос аралдары',
    ms: 'Kepulauan Cocos',
    ru: 'Кокосовые острова',
    tr: 'Cocos Adaları',
    zh: '科科斯群岛',
  },
  mo: {
    en: 'Macau',
    ar: 'ماكاو',
    az: 'Makao',
    de: 'Macao',
    es: 'Macao',
    fa: 'ماکائو',
    fr: 'Macao',
    id: 'Makau',
    it: 'Macao',
    kk: 'Макао',
    ko: '마카오',
    ky: 'Макао',
    ms: 'Macau',
    ru: 'Макао',
    tr: 'Makao',
    zh: '澳门',
  },
  vg: {
    en: 'British Virgin Islands',
    ar: 'جزر العذراء البريطانية',
    az: 'Böyük Britaniyanın Virgin Adaları',
    de: 'Britische Jungferninseln',
    es: 'Islas Vírgenes Británicas',
    fa: 'جزایر ویرجین بریتانیا',
    fr: 'Îles Vierges britanniques',
    id: 'Kepulauan Virgin Britania',
    it: 'Isole Vergini Britanniche',
    kk: 'Британдық Виргин аралдары',
    ko: '영국령 버진아일랜드',
    ky: 'Британ Виргин аралдары',
    ms: 'Kepulauan Virgin British',
    ru: 'Британские Виргинские острова',
    tr: 'Britanya Virgin Adaları',
    zh: '英属维尔京群岛',
  },
  bl: {
    en: 'Saint Barthélemy',
    ar: 'سانت بارتيليمي',
    az: 'Sent-Bartelemi',
    de: 'Saint-Barthélemy',
    es: 'San Bartolomé',
    fa: 'سن بارتلمی',
    fr: 'Saint-Barthélemy',
    id: 'Saint Barthélemy',
    it: 'Saint-Barthélemy',
    kk: 'Сен-Бартелеми',
    ko: '생바르텔레미',
    ky: 'Сент-Бартелеми',
    ms: 'Saint Barthélemy',
    ru: 'Сен-Бартелеми',
    tr: 'Saint Barthélemy',
    zh: '圣巴泰勒米',
  },
  bs: {
    en: 'Bahamas',
    ar: 'الباهاما',
    az: 'Baham adaları',
    de: 'Bahamas',
    es: 'Bahamas',
    fa: 'باهاماس',
    fr: 'Bahamas',
    id: 'Bahamas',
    it: 'Bahamas',
    kk: 'Багам аралдары',
    ko: '바하마',
    ky: 'Багама аралдары',
    ms: 'Bahamas',
    ru: 'Багамы',
    tr: 'Bahamalar',
    zh: '巴哈马',
  },
  um: {
    en: 'United States Minor Outlying Islands',
    ar: 'جزر الولايات المتحدة الصغيرة النائية',
    az: 'ABŞ-a məxsus uzaq adalar',
    de: 'Amerikanisch-Ozeanien',
    es: 'Islas Ultramarinas Menores de Estados Unidos',
    fa: 'جزایر کوچک حاشیه‌ای ایالات متحده',
    fr: 'Îles mineures éloignées des États-Unis',
    id: 'Pulau Terluar Kecil Amerika Serikat',
    it: 'Isole Minori Esterne degli Stati Uniti',
    kk: 'АҚШ-тың алыс аралдары',
    ko: '미국령 군소 제도',
    ky: 'АКШнын алыстагы аралдары',
    ms: 'Pulau Terpencil Kecil Amerika Syarikat',
    ru: 'Малые отдаленные острова США',
    tr: 'ABD Küçük Dış Adaları',
    zh: '美国本土外小岛屿',
  },
  gl: {
    en: 'Greenland',
    ar: 'جرينلاند',
    az: 'Qrenlandiya',
    de: 'Grönland',
    es: 'Groenlandia',
    fa: 'گرینلند',
    fr: 'Groenland',
    id: 'Greenland',
    it: 'Groenlandia',
    kk: 'Гренландия',
    ko: '그린란드',
    ky: 'Гренландия',
    ms: 'Greenland',
    ru: 'Гренландия',
    tr: 'Grönland',
    zh: '格陵兰',
  },
  cv: {
    en: 'Cape Verde',
    ar: 'الرأس الأخضر',
    az: 'Kabo-Verde',
    de: 'Kap Verde',
    es: 'Cabo Verde',
    fa: 'دماغه سبز',
    fr: 'Cap-Vert',
    id: 'Tanjung Verde',
    it: 'Capo Verde',
    kk: 'Кабо-Верде',
    ko: '카보베르데',
    ky: 'Кабо-Верде',
    ms: 'Tanjung Verde',
    ru: 'Кабо-Верде',
    tr: 'Yeşil Burun Adaları',
    zh: '佛得角',
  },
  gm: {
    en: 'Gambia',
    ar: 'غامبيا',
    az: 'Qambiya',
    de: 'Gambia',
    es: 'Gambia',
    fa: 'گامبیا',
    fr: 'Gambie',
    id: 'Gambia',
    it: 'Gambia',
    kk: 'Гамбия',
    ko: '감비아',
    ky: 'Гамбия',
    ms: 'Gambia',
    ru: 'Гамбия',
    tr: 'Gambiya',
    zh: '冈比亚',
  },
  re: {
    en: 'Réunion',
    ar: 'ريونيون',
    az: 'Reyunyon',
    de: 'Réunion',
    es: 'Reunión',
    fa: 'رئونیون',
    fr: 'Réunion',
    id: 'Réunion',
    it: 'Réunion',
    kk: 'Реюньон',
    ko: '레위니옹',
    ky: 'Реюньон',
    ms: 'Réunion',
    ru: 'Реюньон',
    tr: 'Reunion',
    zh: '留尼汪',
  },
  fm: {
    en: 'Micronesia',
    ar: 'ميكرونيزيا',
    az: 'Mikroneziya',
    de: 'Mikronesien',
    es: 'Micronesia',
    fa: 'میکرونزی',
    fr: 'Micronésie',
    id: 'Mikronesia',
    it: 'Micronesia',
    kk: 'Микронезия',
    ko: '미크로네시아',
    ky: 'Микронезия',
    ms: 'Mikronesia',
    ru: 'Микронезия',
    tr: 'Mikronezya',
    zh: '密克罗尼西亚',
  },
  cw: {
    en: 'Curaçao',
    ar: 'كوراساو',
    az: 'Kurasao',
    de: 'Curaçao',
    es: 'Curazao',
    fa: 'کوراسائو',
    fr: 'Curaçao',
    id: 'Curaçao',
    it: 'Curaçao',
    kk: 'Кюрасао',
    ko: '퀴라소',
    ky: 'Кюрасао',
    ms: 'Curaçao',
    ru: 'Кюрасао',
    tr: 'Curaçao',
    zh: '库拉索',
  },
  kp: {
    en: 'North Korea',
    ar: 'كوريا الشمالية',
    az: 'Şimali Koreya',
    de: 'Nordkorea',
    es: 'Corea del Norte',
    fa: 'کره شمالی',
    fr: 'Corée du Nord',
    id: 'Korea Utara',
    it: 'Corea del Nord',
    kk: 'Солтүстік Корея',
    ko: '조선민주주의인민공화국',
    ky: 'Түндүк Корея',
    ms: 'Korea Utara',
    ru: 'Северная Корея',
    tr: 'Kuzey Kore',
    zh: '朝鲜',
  },
  sx: {
    en: 'Sint Maarten',
    ar: 'سانت مارتن',
    az: 'Sint-Marten',
    de: 'Sint Maarten',
    es: 'Sint Maarten',
    fa: 'سینت مارتن',
    fr: 'Sint Maarten',
    id: 'Sint Maarten',
    it: 'Sint Maarten',
    kk: 'Синт-Мартен',
    ko: '신트마르턴',
    ky: 'Синт-Мартен',
    ms: 'Sint Maarten',
    ru: 'Синт-Мартен',
    tr: 'Sint Maarten',
    zh: '荷属圣马丁',
  },
  bv: {
    en: 'Bouvet Island',
    ar: 'جزيرة بوفو',
    az: 'Bouvet adası',
    de: 'Bouvetinsel',
    es: 'Isla Bouvet',
    fa: 'جزیره بووت',
    fr: 'Île Bouvet',
    id: 'Pulau Bouvet',
    it: 'Isola Bouvet',
    kk: 'Бувет аралы',
    ko: '부베섬',
    ky: 'Бувет аралы',
    ms: 'Pulau Bouvet',
    ru: 'Остров Буве',
    tr: 'Bouvet Adası',
    zh: '布韦岛',
  },
  bq: {
    en: 'Bonaire, Sint Eustatius and Saba',
    ar: 'بونير، سينت أوستاتيوس وسابا',
    az: 'Bonaire, Sint Eustatius və Saba',
    de: 'Bonaire, Sint Eustatius und Saba',
    es: 'Bonaire, Sint Eustaquio y Saba',
    fa: 'بونیر، سنت اوستاتیوس و سبا',
    fr: 'Bonaire, Saint-Eustache et Saba',
    id: 'Bonaire, Sint Eustatius dan Saba',
    it: 'Bonaire, Sint Eustatius e Saba',
    kk: 'Бонайр, Синт-Эстатиус және Саба',
    ko: '보네르, 신트 유스타티우스와 사바',
    ky: 'Бонайр, Синт-Эстатиус жана Саба',
    ms: 'Bonaire, Sint Eustatius dan Saba',
    ru: 'Бонайре, Синт-Эстатиус и Саба',
    tr: 'Bonaire, Sint Eustatius ve Saba',
    zh: '博内尔、圣尤斯塔蒂乌斯和萨巴',
  },
};

export function getCountryList(lang: SupportedLanguage = 'en') {
  const r: Country[] = [];
  for (const code in i18n_COUNTRIES) {
    r.push({ code, name: i18n_COUNTRIES[code][lang] });
  }
  return r;
}
